import {
	BookMarked,
	Bot,
	Clapperboard,
	CodeXml,
	Cpu,
	MessageCircle,
	Milestone,
	PersonStanding,
	Popcorn,
	TentTree
} from "lucide-react"

import type { TagsIconMapType } from "@/types/tags-icon-map.types"

import {
	Bootstrap,
	Css,
	EcmaScript,
	Framer,
	Git,
	GitHub,
	GraphQL,
	Html,
	JavaScript,
	Jinja,
	jQuery,
	KendoUI,
	Less,
	Lucide,
	MJML,
	Nextjs,
	NPM,
	ReactHookForm,
	ReactIcon,
	Redux,
	Shadcn,
	Storybook,
	StyledComponents,
	Supabase,
	TailwindCss,
	TanStack,
	TypeScript,
	Vite,
	Zod,
	Zustand
} from "@/icons"

export const tagsIconMap: TagsIconMapType = {
	React: ReactIcon,
	"Next.js": Nextjs,
	TypeScript: TypeScript,
	"Tailwind CSS": TailwindCss,
	"shadcn/ui": Shadcn,
	CSS: Css,
	ES6: EcmaScript,
	HTML: Html,
	JavaScript: JavaScript,
	Git: Git,
	GraphQL: GraphQL,
	Storybook: Storybook,
	"React Hook Form": ReactHookForm,
	Zustand: Zustand,
	Redux: Redux,
	Supabase: Supabase,
	Zod: Zod,
	TanStack: TanStack,
	"TanStack Form": TanStack,
	"TanStack Query": TanStack,
	"TanStack Router": TanStack,
	"TanStack Start": TanStack,
	"TanStack Table": TanStack,
	Vite: Vite,
	Framer: Framer,
	GitHub: GitHub,
	npm: NPM,
	"Styled Components": StyledComponents,
	Bootstrap: Bootstrap,
	jQuery: jQuery,
	Jinja: Jinja,
	"Kendo UI": KendoUI,
	LESS: Less,
	Lucide: Lucide,
	MJML: MJML,
	Tatil: TentTree,
	Frontend: CodeXml,
	Kitap: BookMarked,
	"Yıl Değerlendirmesi": Milestone,
	Film: Popcorn,
	Kişisel: PersonStanding,
	Yorum: MessageCircle,
	Teknoloji: Cpu,
	Dizi: Clapperboard,
	"Yapay Zekâ": Bot
}
