import type { BlogPost } from "@/features/blog/types/blog.types"

export const MOCK_BLOG_POSTS: BlogPost[] = [
	{
		slug: "/imparatorun-imgesi",
		title: "İmparator'un İmgesi",
		description: "Gizem Magemizoğlu'nun kaleminden, Fatih Sultan Mehmed'in kamusal imajı ve imparatorluk siyasetini inceleyen ufuk açıcı bir eser.",
		category: "personal",
		tags: ["Kitap"],
		locale: "tr",
		published: false,
		publishedAt: "2026-06-30",
		coverImage: "/blog/future/imparatorun-imgesi.png",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/imparatorun-imgesi"
	},
	{
		slug: "/virastack-ai",
		title: "ViraStack AI: Yapay Zekâya Mimari Disiplin",
		description: "ViraStack AI, React projelerinde yapay zekânın ürettiği kodu mimari kurallarla disipline eden .mdc bağlam dosyaları ve üretim protokolleri sunar.",
		category: "technical",
		tags: ["ViraStack", "Yapay Zekâ"],
		locale: "tr",
		published: true,
		publishedAt: "2026-06-30",
		coverImage: "/blog/2026/04-05/virastack.jpeg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/virastack-ai",
		series: "virastack",
		seriesOrder: 2
	},
	{
		slug: "/footy-ile-rekabete-hazir-misin",
		title: "Futbol Bilgini Sahaya Yansıt: Footy ile Rekabete Hazır Mısın?",
		description: "Gerçek futbol tutkunlarını tek bir çatı altında toplayan, futbol bilgisini eğlenceye ve kıyasıya bir rekabete dönüştüren Footy platformu yayında!",
		category: "personal",
		tags: ["Proje"],
		locale: "tr",
		published: true,
		publishedAt: "2026-06-28",
		coverImage: "/blog/2026/06-28/futbol-manyagi.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/footy-ile-rekabete-hazir-misin",
		mediumUrl: "https://omergulcicek.medium.com/futbol-bilgini-sahaya-yans%C4%B1t-footy-ile-rekabete-haz%C4%B1r-m%C4%B1s%C4%B1n-6877cba0208e"
	},
	{
		slug: "/ilgi-alanlarinizi-tek-tikla-takviminize-ekleyin",
		title: "İlgi Alanlarınızı Tek Tıkla Takviminize Ekleyin",
		description: "Daha önce Takvim Abonelikleriyle Zamanı Zenginleştirin yazımda duyurduğum tematik takvim abonelikleri projesini baştan aşağı yeniledim. İçerik...",
		category: "personal",
		tags: ["Proje"],
		locale: "tr",
		published: true,
		publishedAt: "2026-06-28",
		coverImage: "/blog/2026/06-28/takvim-onizleme.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/ilgi-alanlarinizi-tek-tikla-takviminize-ekleyin",
		mediumUrl: "https://medium.com/@omergulcicek/i%CC%87lgi-alanlar%C4%B1n%C4%B1z%C4%B1-tek-t%C4%B1kla-takviminize-ekleyin-98ea44e1ee52"
	},
	{
		slug: "/medya-kusatmasi-ve-ruhsuz-egitim-manevi-bosluktaki-zombi-nesil",
		title: "Medya Kuşatması ve Ruhsuz Eğitim: Manevi Boşluktaki Zombi Nesil",
		description: "Okullardaki şiddetin temelindeki manevi boşluğu, ruhsuz eğitim sistemini ve medya kuşatmasıyla zombileşen gençliği irdeleyen bir zihniyet analizi.",
		category: "personal",
		tags: ["Düşünce"],
		locale: "tr",
		published: true,
		publishedAt: "2026-04-16",
		coverImage: "/blog/2026/04-16/diziler.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/medya-kusatmasi-ve-ruhsuz-egitim-manevi-bosluktaki-zombi-nesil"
	},
	{
		slug: "/dijital-bir-hayalet-gunlugu",
		title: "Dijital Bir Hayalet Günlüğü",
		description: "Algoritmalar, derin içerik ve görünürlük: Barış Manço örneğinden bugünün dijital varlık mücadelesine.",
		category: "personal",
		tags: ["Düşünce"],
		locale: "tr",
		published: true,
		publishedAt: "2026-04-09",
		coverImage: "/blog/2026/04-08/omer-demirbag.jpeg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/dijital-bir-hayalet-gunlugu"
	},
	{
		slug: "/frontend-ekosistemi-insa-etmek",
		title: "ViraStack: Frontend Ekosistemi",
		description: "ViraStack nasıl doğdu? Turkuaz CSS'ten açık kaynak bir frontend ekosistemine uzanan kişisel yolculuğum ve bu yapının arkasındaki motivasyon.",
		category: "technical",
		tags: ["ViraStack"],
		locale: "tr",
		published: true,
		publishedAt: "2026-04-05",
		coverImage: "/blog/2026/04-05/virastack.jpeg",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/frontend-ekosistemi-insa-etmek",
		featured: true,
		mediumUrl: "https://omergulcicek.medium.com/frontend-ekosistemi-insa-etmek-78111c2d96dc",
		series: "virastack",
		seriesOrder: 1
	},
	{
		slug: "/gelenekten-gelecege-ramazan-adabi-ve-teknik-hedefler",
		title: "Gelenekten Geleceğe: Ramazan Adabı",
		description: "Bu sene Ramazan'ı her anlamda hakkını vererek yaşamak, kendime hem ruhsal hem kültürel anlamda bir şeyler katmak niyetindeyim. Eski Ramazan kültürünü bugüne...",
		category: "personal",
		tags: ["Düşünce"],
		locale: "tr",
		published: true,
		publishedAt: "2026-02-17",
		coverImage: "/blog/2026/02-17/ramazan.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/gelenekten-gelecege-ramazan-adabi-ve-teknik-hedefler",
		mediumUrl: "https://medium.com/@omergulcicek/gelenekten-gelece%C4%9Fe-ramazan-adab%C4%B1-ve-teknik-hedefler-589dfd1d8b72"
	},
	{
		slug: "/kaide-ai-native-architecture-kit",
		title: "Kaide: AI-Native Architecture Kit",
		description: "An architectural standard optimized for modern web projects, making code more readable and manageable for AI assistants: Kaide Architecture Kit.",
		category: "technical",
		tags: ["Next.js", "TanStack"],
		locale: "en",
		published: true,
		publishedAt: "2026-02-14",
		coverImage: "/blog/2026/02-14/kaide.png",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/kaide-ai-native-architecture-kit",
		featured: true,
		translationOf: "/kaide-yapay-zeka-odakli-mimari-kit"
	},
	{
		slug: "/kaide-yapay-zeka-odakli-mimari-kit",
		title: "Kaide: Yapay Zekâ Odaklı Mimari Kit",
		description: "Yapay zeka asistanlarıyla uyumlu, modern web projeleri için optimize edilmiş, okunabilir ve yönetilebilir bir mimari standardı: Kaide Architecture Kit.",
		category: "technical",
		tags: ["Next.js", "TanStack"],
		locale: "tr",
		published: true,
		publishedAt: "2026-02-14",
		coverImage: "/blog/2026/02-14/kaide.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/kaide-yapay-zeka-odakli-mimari-kit",
		mediumUrl: "https://omergulcicek.medium.com/kaide-yapay-zek%C3%A2-odakl%C4%B1-mimari-kit-d323a9b81552",
		translatedTo: "/kaide-ai-native-architecture-kit"
	},
	{
		slug: "/documentation-for-machines-llms-txt",
		title: "Documentation for Machines: llms.txt",
		description: "We are now targeting AI agents in the web world. This article explores how to use the llms.txt format to make projects more readable for LLMs.",
		category: "technical",
		tags: ["Yapay Zekâ"],
		locale: "en",
		published: true,
		publishedAt: "2026-02-04",
		coverImage: "/blog/2026/02-04/llms.png",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/documentation-for-machines-llms-txt",
		translationOf: "/makineler-icin-dokumantasyon-llms-txt"
	},
	{
		slug: "/makineler-icin-dokumantasyon-llms-txt",
		title: "Makineler İçin Dokümantasyon: llms.txt",
		description: "Web dünyasında artık yapay zeka ajanları da hedef kitlemiz. llms.txt formatı ile LLM'ler için projelerimizi nasıl daha okunabilir hale getireceğimizi...",
		category: "technical",
		tags: ["Yapay Zekâ"],
		locale: "tr",
		published: true,
		publishedAt: "2026-02-04",
		coverImage: "/blog/2026/02-04/llms.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/makineler-icin-dokumantasyon-llms-txt",
		translatedTo: "/documentation-for-machines-llms-txt"
	},
	{
		slug: "/tanstack-start-injected-head-scripts-hatasi-cozumu",
		title: "TanStack Start: tanstack-start-injected-head-scripts Hatası ve Çözümü",
		description: "TanStack Start projelerinde karşılaşılan 'Injected head scripts' hidrasyon hatasının nedenleri ve Supabase gibi script enjekte eden eklentilerle çözüm...",
		category: "technical",
		tags: ["TanStack", "Supabase", "Vite"],
		locale: "tr",
		published: true,
		publishedAt: "2026-02-03",
		coverImage: "/blog/2026/02-03/injected.png",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/tanstack-start-injected-head-scripts-hatasi-cozumu",
		mediumUrl: "https://medium.com/@omergulcicek/tanstack-start-tanstack-start-injected-head-scripts-hatas%C4%B1-ve-%C3%A7%C3%B6z%C3%BCm%C3%BC-69de117093a0",
		translatedTo: "/tanstack-start-resolving-the-tanstack-start-injected-head-scripts-error"
	},
	{
		slug: "/tanstack-start-resolving-the-tanstack-start-injected-head-scripts-error",
		title: "TanStack Start: Resolving the tanstack-start-injected-head-scripts Error",
		description: "Causes and solutions for the 'Injected head scripts' hydration error encountered in TanStack Start projects, especially when using plugins like Supabase.",
		category: "technical",
		tags: ["TanStack", "Supabase", "Vite"],
		locale: "en",
		published: true,
		publishedAt: "2026-02-03",
		coverImage: "/blog/2026/02-03/injected.png",
		readingTimeMinutes: 5,
		canonicalUrl: "https://omergulcicek.com/blog/tanstack-start-resolving-the-tanstack-start-injected-head-scripts-error",
		mediumUrl: "https://medium.com/@omergulcicek/tanstack-start-resolving-the-tanstack-start-injected-head-scripts-error-c1eecbf31735",
		translationOf: "/tanstack-start-injected-head-scripts-hatasi-cozumu"
	},
	{
		slug: "/see",
		title: "See",
		description: "Apple TV+ yapımı olan See, uzak bir gelecekte insanlığın görme yetisini kaybettiği ve 'görmenin' bir efsane, hatta tehlikeli bir günah sayıldığı bir...",
		category: "personal",
		tags: ["Dizi"],
		locale: "tr",
		published: true,
		publishedAt: "2026-02-02",
		coverImage: "/blog/future/see.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/see"
	},
	{
		slug: "/react-state-yonetim-mimarisi",
		title: "React State Yönetim Mimarisi",
		description: "State yönetimi tartışmaları genellikle 'Hangi kütüphaneyi kullanmalıyım?' sorusuyla başlar. Oysa asıl soru şudur: Yönettiğim state'in doğası ne? Bu...",
		category: "technical",
		tags: ["React", "TanStack"],
		locale: "tr",
		published: true,
		publishedAt: "2026-02-01",
		coverImage: "/blog/2026/02-01/passing-props.png",
		readingTimeMinutes: 6,
		canonicalUrl: "https://omergulcicek.com/blog/react-state-yonetim-mimarisi",
		mediumUrl: "https://medium.com/@omergulcicek/react-state-y%C3%B6netim-mimarisi-cec5ad6043fb"
	},
	{
		slug: "/react-ai-stack-2026",
		title: "2026 için React ve AI Stack'i",
		description: "Yapay zekanın kod yazma süreçlerimizi nasıl değiştirdiğini ve 2026'ya girerken neden React + AI araçlarının endüstri standardı haline geldiğini inceleyen...",
		category: "technical",
		tags: ["Frontend", "Yapay Zekâ"],
		locale: "tr",
		published: true,
		publishedAt: "2026-01-28",
		coverImage: "/blog/2026/01-28/react-stack.png",
		readingTimeMinutes: 6,
		canonicalUrl: "https://omergulcicek.com/blog/react-ai-stack-2026",
		featured: true,
		mediumUrl: "https://medium.com/@omergulcicek/2026-i%C3%A7in-react-ve-ai-stacki-f3f9cc815674"
	},
	{
		slug: "/2025ten-2026ya-degerlendirme-ve-hedefler",
		title: "2025'ten 2026'ya: Değerlendirme ve Hedefler",
		description: "2025, hayatımın hem kişisel hem profesyonel tarafında keskin dönüşümlerin yaşandığı, zorlayıcı ama öğretici bir yıl oldu. Yerleşik düzenimin...",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2026-01-01",
		coverImage: "/blog/2025/12-31/github-3.png",
		readingTimeMinutes: 6,
		canonicalUrl: "https://omergulcicek.com/blog/2025ten-2026ya-degerlendirme-ve-hedefler",
		series: "yillik-degerlendirme",
		seriesOrder: 10
	},
	{
		slug: "/2026da-hayatimiza-girecek-yeni-css-ozellikleri",
		title: "2026'da Hayatımıza Girecek Yeni CSS Özellikleri",
		description: "2026 yılı, CSS dünyası için birçok heyecan verici yenilik getiriyor. Bu yazıda, web geliştiricilerin mutlaka bilmesi gereken yeni CSS özelliklerini...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2025-12-25",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2026da-hayatimiza-girecek-yeni-css-ozellikleri",
		interactive: true,
		featured: true,
		mediumUrl: "https://omergulcicek.medium.com/2026da-hayat%C4%B1m%C4%B1za-girecek-yeni-css-%C3%B6zellikleri-f48158357b77"
	},
	{
		slug: "/ai-caginda-frontend-bitti-mi",
		title: "AI Çağında Frontend Bitti mi?",
		description: "Herkes 'frontend bitti, öldü' diyor. Pandemi dönemindeki agresif işe alımların ardından şişen ekipler, ekonomik daralmayla birlikte küçülmeye ve ardı...",
		category: "technical",
		tags: ["Frontend", "Yapay Zekâ"],
		locale: "tr",
		published: true,
		publishedAt: "2025-12-01",
		coverImage: "/blog/2025/12-01/frontend.png",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/ai-caginda-frontend-bitti-mi",
		mediumUrl: "https://omergulcicek.medium.com/ai-%C3%A7a%C4%9F%C4%B1nda-frontend-bitti-mi-17fedba66f96?postPublishedType=initial"
	},
	{
		slug: "/yan-yana",
		title: "Soyut Dışavurumcu Bir Dostluğun Anatomisi Veyahut Yan Yana",
		description: "2011 yapımı Can Dostum'un uyarlaması olan Yan Yana, Haluk Bilginer ve Feyyaz Yiğit'in buluşmasıyla daha ilk anlarda güçlü bir dikkat uyandırıyor....",
		category: "personal",
		tags: ["Film"],
		locale: "tr",
		published: true,
		publishedAt: "2025-11-28",
		coverImage: "/blog/2025/11-28/yan-yana.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/yan-yana"
	},
	{
		slug: "/yapay-zekanin-sorunlari",
		title: "Yapay Zekânın Sorunları",
		description: "Bu yazı, Google'da baş mühendis olarak çalışan Addy Osmani'nin Zed blogunda yayımlanan 'AI's 70% Problem' başlıklı makalesinin özetlenmiş Türkçe...",
		category: "technical",
		tags: ["Yapay Zekâ"],
		locale: "tr",
		published: true,
		publishedAt: "2025-11-18",
		coverImage: "/blog/2025/11-18/addy-osmani.png",
		readingTimeMinutes: 5,
		canonicalUrl: "https://omergulcicek.com/blog/yapay-zekanin-sorunlari",
		mediumUrl: "https://omergulcicek.medium.com/yapay-zek%C3%A2n%C4%B1n-sorunlar%C4%B1-57ab1bf5e335?postPublishedType=initial"
	},
	{
		slug: "/nizam-nextjs-16-boilerplate",
		title: "Nizam - Next.js 16 Boilerplate",
		description: "Modern web uygulamalarını hızlı, güvenli ve ölçeklenebilir bir şekilde inşa etmek için hazırladığım Next.js 16 boilerplate projesi: Nizam.",
		category: "technical",
		tags: ["Next.js", "TanStack"],
		locale: "tr",
		published: true,
		publishedAt: "2025-11-06",
		coverImage: "/blog/2025/11-05/nizam.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/nizam-nextjs-16-boilerplate",
		mediumUrl: "https://omergulcicek.medium.com/nizam-next-js-16-boilerplate-3015d8945f39",
		translatedTo: "/nizam-nextjs-16-boilerplate-en"
	},
	{
		slug: "/nizam-nextjs-16-boilerplate-en",
		title: "Nizam - Next.js 16 Boilerplate (EN)",
		description: "Introducing Nizam: A Next.js 16 boilerplate designed to build modern web applications quickly, securely, and enjoyably.",
		category: "technical",
		tags: ["Next.js", "TanStack"],
		locale: "en",
		published: true,
		publishedAt: "2025-11-05",
		coverImage: "/blog/2025/11-05/nizam.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/nizam-nextjs-16-boilerplate-en",
		mediumUrl: "https://omergulcicek.medium.com/nizam-next-js-16-boilerplate-en-59fdf4872f3f",
		translationOf: "/nizam-nextjs-16-boilerplate"
	},
	{
		slug: "/nextjs-16-turbopack-cache-components-ve-yeni-mimari-donemi",
		title: "Next.js 16: Turbopack, Cache Components ve Yeni Mimari Dönemi",
		description: "Next.js 16, 21 Ekim 2025’te, Next.js Conf 2025 öncesinde yayınlandı. Bu sürüm, framework’ün performans, önbellekleme ve geliştirici deneyimi...",
		category: "technical",
		tags: ["Next.js"],
		locale: "tr",
		published: true,
		publishedAt: "2025-10-23",
		coverImage: "/blog/2025/10-23/nextjs-16.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/nextjs-16-turbopack-cache-components-ve-yeni-mimari-donemi",
		featured: true,
		mediumUrl: "https://omergulcicek.medium.com/next-js-16-turbopack-cache-components-ve-yeni-mimari-d%C3%B6nemi-5ed8018ccde1"
	},
	{
		slug: "/google-harita-listelerim",
		title: "Google Maps Listelerim",
		description: "Bir şehirde dolaşırken bazen rastgele bir sokağın köşesinde gizli bir kafe, eski bir türbe ya da unutulmuş bir müze çıkıverir karşınıza - özellikle...",
		category: "personal",
		tags: ["Proje"],
		locale: "tr",
		published: true,
		publishedAt: "2025-10-20",
		coverImage: "/blog/2025/10-20/google-maps.png",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/google-harita-listelerim",
		mediumUrl: "https://omergulcicek.medium.com/google-maps-listelerim-83291fedbc9d"
	},
	{
		slug: "/kaliteli-yazilimci-nasil-olunur",
		title: "Kaliteli Yazılımcı Nasıl Olunur?",
		description: "10 yılı aşkın süredir yazılım sektöründeyim. Bu süreçte farklı ölçeklerde birçok şirkette çalıştım; kimi zaman harika ekiplerle verimli işler...",
		category: "technical",
		tags: ["Frontend"],
		locale: "tr",
		published: true,
		publishedAt: "2025-10-14",
		coverImage: "/blog/2025/10-14/yazilimci.png",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/kaliteli-yazilimci-nasil-olunur",
		mediumUrl: "https://omergulcicek.medium.com/kaliteli-yaz%C4%B1l%C4%B1mc%C4%B1-nas%C4%B1l-olunur-9b357ae2bc3c"
	},
	{
		slug: "/fatih-sultan-mehmed-dogunun-ve-batinin-efendisi",
		title: "Fâtih Sultan Mehmed - Doğu’nun ve Batı’nın Efendisi",
		description: "İlber Ortaylı, Türkiye’nin büyük tarihçi yazarlarından ve yorumcularından biri olarak, tarihimizin en önemli hükümdarı Fatih Sultan Mehmed’i kaleme...",
		category: "personal",
		tags: ["Kitap"],
		locale: "tr",
		published: true,
		publishedAt: "2025-10-02",
		coverImage: "/blog/2025/10-02/fatih.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/fatih-sultan-mehmed-dogunun-ve-batinin-efendisi"
	},
	{
		slug: "/takvim-abonelikleriyle-zamani-zenginlestirin",
		title: "Takvim Abonelikleriyle Zamanı Zenginleştirin",
		description: "Apple Takvim'e tek tıkla abone olabileceğiniz, özenle derlenmiş tematik takvimler hazırladım. Her bir etkinlikte kısa açıklamalar, gerekiyorsa kaynak...",
		category: "personal",
		tags: ["Proje"],
		locale: "tr",
		published: true,
		publishedAt: "2025-09-19",
		coverImage: "/blog/2025/09-19/takvim-ornek.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/takvim-abonelikleriyle-zamani-zenginlestirin",
		mediumUrl: "https://omergulcicek.medium.com/takvim-abonelikleriyle-zaman%C4%B1-zenginle%C5%9Ftirin-7977730e99a3"
	},
	{
		slug: "/gunumuz-turkiyesi-2025",
		title: "Günümüz Türkiyesi 2025",
		description: "Uzun zamandır gözlem yapıp, gözlemlerimi yazıya dökmeyi seviyorum. Bu metin; aklımda birikenleri, sokakta, ekranda, işte gördüklerimi not aldığım bir...",
		category: "personal",
		tags: ["Düşünce"],
		locale: "tr",
		published: true,
		publishedAt: "2025-09-16",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/gunumuz-turkiyesi-2025"
	},
	{
		slug: "/frontend-calisma-ortamim-cursor-eklentiler",
		title: "Frontend Çalışma Ortamım: Cursor, Eklentiler ve Daha Fazlası",
		description: "Bu makalede kendi frontend geliştirme ortamımı, kullandığım araçları, eklentileri ve proje standartlarımı paylaşmak istiyorum. IDE tercihimden...",
		category: "technical",
		tags: ["Yapay Zekâ"],
		locale: "tr",
		published: true,
		publishedAt: "2025-08-13",
		coverImage: "/blog/2025/08-13/calisma-masam.JPG",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/frontend-calisma-ortamim-cursor-eklentiler",
		mediumUrl: "https://omergulcicek.medium.com/frontend-%C3%A7al%C4%B1%C5%9Fma-ortam%C4%B1m-cursor-eklentiler-ve-daha-fazlas%C4%B1-d0b63064fe25"
	},
	{
		slug: "/sitemin-yeni-arayuzune-hosgeldiniz",
		title: "Sitemin Yeni Arayüzüne Hoşgeldiniz",
		description: "Merhaba! Uzun bir aradan sonra kişisel sitemi yeniden tasarladım ve bu yazımda bu yenileme sürecini detaylandırmak istiyorum. Sitemi modern frontend...",
		category: "technical",
		tags: ["Site Yenileme", "Next.js"],
		locale: "tr",
		published: true,
		publishedAt: "2025-07-27",
		coverImage: "/blog/2025/07-27/avatars.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/sitemin-yeni-arayuzune-hosgeldiniz",
		mediumUrl: "https://omergulcicek.medium.com/sitemin-yeni-aray%C3%BCz%C3%BCne-ho%C5%9Fgeldiniz-126ce241ea47",
		series: "site-yenileme",
		seriesOrder: 3
	},
	{
		slug: "/nevsehir-tatili",
		title: "Nevşehir Tatili",
		description: "2025 Temmuz'un ilk haftasında, Kapadokya'nın büyüleyici atmosferini keşfetmek için Nevşehir'e doğru yola çıktım. 4 gecelik bu tatilde balon seyri,...",
		category: "personal",
		tags: ["Seyahat"],
		locale: "tr",
		published: true,
		publishedAt: "2025-07-26",
		coverImage: "/blog/2025/07-26/balon.JPG",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/nevsehir-tatili",
		mediumUrl: "https://omergulcicek.medium.com/nev%C5%9Fehir-tatili-16233f3723be"
	},
	{
		slug: "/nextjs-15-boilerplate",
		title: "Next.js 15 Boilerplate",
		description: "Merhaba! Bu yazıda, en güncel teknolojileri kullanarak geliştirdiğim Next.js 15 Boilerplate projesini sizlerle paylaşmak istiyorum. Bu şablon, modern...",
		category: "technical",
		tags: ["Next.js", "TypeScript", "shadcn/ui"],
		locale: "tr",
		published: true,
		publishedAt: "2025-07-23",
		coverImage: "/blog/2025/07-23/boilerplate.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/nextjs-15-boilerplate",
		mediumUrl: "https://omergulcicek.medium.com/next-js-15-boilerplate-7d34c8be6b16"
	},
	{
		slug: "/react-parola-inputlari-icin-goster-gizle-hooku",
		title: "React Parola Inputları İçin Göster/Gizle Hooku",
		description: "@omergulcicek/password-input React projelerinde parola inputları için göster/gizle işlevselliği eklemek için bir çok şey yapmamız gerekiyor. State...",
		category: "technical",
		tags: ["React", "npm"],
		locale: "tr",
		published: true,
		publishedAt: "2025-06-19",
		coverImage: "/blog/2025/06-16/password-input.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/react-parola-inputlari-icin-goster-gizle-hooku",
		mediumUrl: "https://omergulcicek.medium.com/react-parola-inputlar%C4%B1-i%C3%A7in-g%C3%B6ster-gizle-hooku-1f0085624887"
	},
	{
		slug: "/react-hook-form-icin-akilli-mask-ve-dogrulama",
		title: "React Hook Form İçin Akıllı Mask ve Doğrulama",
		description: "@omergulcicek/forms React projelerinde form doğrulama ve input mask işlemleriyle uğraşmak çoğu zaman zahmetli olabiliyor. Bu ihtiyacı karşılamak için...",
		category: "technical",
		tags: ["React", "npm"],
		locale: "tr",
		published: true,
		publishedAt: "2025-06-09",
		coverImage: "/blog/2025/06-09/forms-mask.png",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/react-hook-form-icin-akilli-mask-ve-dogrulama",
		mediumUrl: "https://medium.com/kodcular/react-hook-form-i%C3%A7in-ak%C4%B1ll%C4%B1-mask-ve-do%C4%9Frulama-97dfe79d9123"
	},
	{
		slug: "/css-attr-icin-yeni-yetkinlikler",
		title: "CSS attr() İçin Yeni Yetkinlikler",
		description: "CSS attr() fonksiyonunun yeni yetkinlikleri sayesinde renkler, uzunluklar ve sayısal değerler CSS değişkenlerine ihtiyaç duymadan doğrudan HTML üzerinden...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2025-03-22",
		coverImage: "/blog/2025/03-22/css-attr.png",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/css-attr-icin-yeni-yetkinlikler",
		mediumUrl: "https://omergulcicek.medium.com/css-attr-i%CC%87%C3%A7in-yeni-yetkinlikler-47c9b2fabe10"
	},
	{
		slug: "/tailwind-css-v4",
		title: "Tailwind CSS v4",
		description: "Frontend dünyasında popülerleşen Tailwind CSS, v4.0 sürümüyle karşımıza çıktı. Yeni sürümüyle esneklik ve performansı artırıyor.",
		category: "technical",
		tags: ["Tailwind CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2025-02-07",
		coverImage: "/blog/2025/01-29/tailwind-css-v4.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/tailwind-css-v4",
		mediumUrl: "https://omergulcicek.medium.com/tailwind-css-v4-0-7678b29262f3?source=user_profile_page"
	},
	{
		slug: "/2025-yilinda-frontend-developer-olmak",
		title: "2025 Yılında Frontend Developer Olmak",
		description: "Frontend dünyası, neler bilmeliyiz? Frontend dünyası, geçmişte Bootstrap ve jQuery'in hakimiyetindeydi. Hızla gelişen JavaScript sayesinde React,...",
		category: "technical",
		tags: ["Next.js", "TanStack", "TypeScript"],
		locale: "tr",
		published: true,
		publishedAt: "2025-01-20",
		coverImage: "/blog/2025/01-20/react-typescript.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2025-yilinda-frontend-developer-olmak",
		mediumUrl: "https://omergulcicek.medium.com/2025-y%C4%B1l%C4%B1nda-frontend-developer-olmak-774e74ae355c"
	},
	{
		slug: "/react-virtualization-buyuk-verilerin-ekranda-verimli-gosterimi",
		title: "React Virtualization: Büyük Verilerin Ekranda Verimli Gösterimi",
		description: "React Virtualization Nedir? React Virtualization, büyük veri setleriyle çalışan React uygulamalarında performans optimizasyonu sağlamaya yönelik bir...",
		category: "technical",
		tags: ["React"],
		locale: "tr",
		published: true,
		publishedAt: "2025-01-10",
		coverImage: "/blog/2025/01-10/virtualization.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/react-virtualization-buyuk-verilerin-ekranda-verimli-gosterimi",
		mediumUrl: "https://omergulcicek.medium.com/react-virtualization-b%C3%BCy%C3%BCk-verilerin-ekranda-verimli-g%C3%B6sterimi-a91b9e6c6e37"
	},
	{
		slug: "/react-19-ile-gelen-yenilik-use-optimistic-hook-kullanimi",
		title: "React 19 ile Gelen Yenilik: useOptimistic Hook Kullanımı",
		description: "React 19 ile hayatımıza giren useOptimistic hook'u sayesinde, sunucu yanıtını beklemeden UI güncellemelerini anında yansıtarak kullanıcı deneyimini...",
		category: "technical",
		tags: ["React"],
		locale: "tr",
		published: true,
		publishedAt: "2025-01-06",
		coverImage: "/blog/2025/01-06/useOptimistic.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/react-19-ile-gelen-yenilik-use-optimistic-hook-kullanimi",
		mediumUrl: "https://omergulcicek.medium.com/react-19-ile-gelen-yenilik-useoptimistic-hook-kullan%C4%B1m%C4%B1-eebe5cb6a732"
	},
	{
		slug: "/frontendin-parlayan-yildizi-shadcn-ui-ile-tanisin",
		title: "Frontend'in Parlayan Yıldızı: shadcn/ui ile Tanışın",
		description: "shadcn/ui, geliştiricilerin uygulamalarına hızlı ve kolay bir şekilde entegre edebilecekleri, güzel tasarlanmış ve yeniden kullanılabilir...",
		category: "technical",
		tags: ["shadcn/ui"],
		locale: "tr",
		published: true,
		publishedAt: "2025-01-04",
		coverImage: "/blog/2025/01-04/shadcn-ui.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/frontendin-parlayan-yildizi-shadcn-ui-ile-tanisin",
		mediumUrl: "https://omergulcicek.medium.com/frontendin-parlayan-y%C4%B1ld%C4%B1z%C4%B1-shadcn-ui-ile-tan%C4%B1%C5%9F%C4%B1n-d0e6b821b4ec"
	},
	{
		slug: "/2025-hedeflerim",
		title: "2025 Hedeflerim",
		description: "Yeni bir yıl, yeni hayaller, yeni hedefler... 🧺 Alınacaklar Listesi Bu yıl, inşallah evlilik yolunda önemli adımlar atmayı planlıyorum....",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2025-01-01",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/2025-hedeflerim",
		series: "yillik-degerlendirme",
		seriesOrder: 9
	},
	{
		slug: "/2024-degerlendirmesi",
		title: "2024 Değerlendirmesi",
		description: "Her yıl sonunda o yılı değerlendirip, yeni yıla hedeflerimi belirliyorum. 2019'dan bu yana bunu kişisel sitemde yazıyorum; sadece 2023 yılında fire...",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2024-12-31",
		coverImage: "/blog/2024/12-31/alisgidis.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2024-degerlendirmesi",
		series: "yillik-degerlendirme",
		seriesOrder: 8
	},
	{
		slug: "/kisisel-sitemin-yeni-arayuzu-nextjs-ve-tailwind-css-ile-gelistirildi",
		title: "Kişisel Sitemin Yeni Arayüzü Next.js ve Tailwind CSS ile Geliştirildi",
		description: "Merhaba! Uzun bir ara vermiştim, ancak artık kişisel sitemde yeniden yazılar paylaşmaya başladım. Bu yazımda, sitemin yeni versiyonunu neden ve nasıl...",
		category: "technical",
		tags: ["Site Yenileme", "Next.js"],
		locale: "tr",
		published: true,
		publishedAt: "2024-12-29",
		coverImage: "/blog/2024/12-29/filters.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/kisisel-sitemin-yeni-arayuzu-nextjs-ve-tailwind-css-ile-gelistirildi",
		series: "site-yenileme",
		seriesOrder: 2
	},
	{
		slug: "/2022-degerlendirmesi",
		title: "2022 Değerlendirmesi",
		description: "2022'yi geride bıraktık. Dolu dolu ve en verimli senelerimden birisi oldu. Yıl içerisindeki hedeflerimin temelinde daha hareketli, gezgin, sosyal bir...",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2022-12-31",
		coverImage: "/blog/2022/12-31/maps.jpg",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2022-degerlendirmesi",
		series: "yillik-degerlendirme",
		seriesOrder: 7
	},
	{
		slug: "/2022-css-istatistikleri",
		title: "2022 CSS İstatistikleri",
		description: "2022 yılı geride kalırken, CSS ile ilgili güzel istatistikler açıklandı. Bunları birlikte inceleyelim. En Sık Kullanılan CSS Class'ları 2020 ve...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2022-10-09",
		coverImage: "/blog/2022/10-09/en-populer-css-siniflari.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/2022-css-istatistikleri"
	},
	{
		slug: "/grid-template-areas-ile-layout-olusturmak",
		title: "Grid Template Areas ile Layout Oluşturmak",
		description: "CSS Grid ile layout'u oluşturmak çok kolay ve fonksiyonel. Bu makalede grid özelliklerinden olan özelliği ile HTML bileşenlerimizi nasıl component...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2022-09-09",
		coverImage: "/blog/2022/09-09/grid-template-areas-ile-layout-olusturmak-1.jpg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/grid-template-areas-ile-layout-olusturmak"
	},
	{
		slug: "/css-object-view-box",
		title: "CSS Object View Box",
		description: "CSS'te bir resmin istediğimiz bir bölümünü kırpmamız için doğal bir yöntem yoktu. Ya resmi saran farklı bir elemente ihtiyacımız vardı (_ gibi_) yada...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2022-06-26",
		coverImage: "/blog/2022/06-26/crop-image-css.png",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/css-object-view-box"
	},
	{
		slug: "/kisisel-sitemin-nextjs-versiyonu",
		title: "Kişisel Sitemin Next.js Versiyonu",
		description: "Düzenli aralıklarla kişisel sitemi farklı yazılım dilleriyle baştan yazıyorum. Teknolojinin yanı sıra, tasarımsal olarakta daha minimal, sade ve şık...",
		category: "technical",
		tags: ["Site Yenileme", "Next.js"],
		locale: "tr",
		published: true,
		publishedAt: "2022-04-22",
		coverImage: "/blog/2022/04-22/renk.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/kisisel-sitemin-nextjs-versiyonu",
		series: "site-yenileme",
		seriesOrder: 1
	},
	{
		slug: "/styled-component-ile-dinamik-css-yazmak",
		title: "Styled Component ile Dinamik CSS Yazmak",
		description: "Çalıştığım projede tasarımı dinamik olarak render edilen componentlere ihtiyacımız oldu. Detaylandırmak gerekirse, default bir butonumuz var fakat bu...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2022-01-25",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/styled-component-ile-dinamik-css-yazmak"
	},
	{
		slug: "/2022-hedeflerim",
		title: "2022 Hedeflerim",
		description: "Yeni bir yıl, yeni hayaller, yeni hedefler... Geride bıraktığımız senede hedeflerimi büyük oranda başarmıştım. Yeni yılda çok daha hareketli, gezgin,...",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2022-01-01",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2022-hedeflerim",
		mediumUrl: "https://omergulcicek.medium.com/2022-hedeflerim-69c889488716",
		series: "yillik-degerlendirme",
		seriesOrder: 6
	},
	{
		slug: "/2021-degerlendirmesi",
		title: "2021 Değerlendirmesi",
		description: "Bu makalede aşağıdaki başlıklar var: - 2021'nin Kısa Özeti - Alınacaklar Listesi - İngilizce - İş ve Eğitim - Satranç - Kitap - Yazılım - Sağlık -...",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2021-12-31",
		coverImage: "/blog/2021/12-31/duolingo-2021.jpg",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2021-degerlendirmesi",
		series: "yillik-degerlendirme",
		seriesOrder: 5
	},
	{
		slug: "/css-container-sorgulari",
		title: "CSS Container Sorguları",
		description: "Responsive Design kavramı 25 Mayıs 2010 tarihinde Ethan Marcotte adlı bir arayüz tasarımcısı sayesinde hayatımıza girmişti. Responsive Web Design...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2021-11-26",
		coverImage: "/blog/2021/11-26/responsive-problem-1.jpg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/css-container-sorgulari"
	},
	{
		slug: "/javascript-selectorlerinin-calisma-hizlari",
		title: "JavaScript Selectorlerinin Çalışma Hızları",
		description: "Her yiğidin yoğurt yiğişi ayrıdır, bir kodu birden çok şekilde yazabilirsiniz. Hepsi doğru çıktığı verebilir fakat performans anlamında birbirlerine...",
		category: "technical",
		tags: ["JavaScript"],
		locale: "tr",
		published: true,
		publishedAt: "2021-10-29",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/javascript-selectorlerinin-calisma-hizlari"
	},
	{
		slug: "/izmir-marmaris-oludeniz-tatili",
		title: "İzmir, Marmaris, Ölüdeniz Tatili",
		description: "15 Temmuz sabahı bavullarımızı alıp 4 üniversite arkadaşım ile Fethiye'ye doğru yola çıktık. Güzergah üzerinde önce İzmir'i gezdik, ardından Marmaris...",
		category: "personal",
		tags: ["Seyahat"],
		locale: "tr",
		published: true,
		publishedAt: "2021-08-09",
		coverImage: "/blog/2021/08-09/izmir.jpg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/izmir-marmaris-oludeniz-tatili"
	},
	{
		slug: "/csste-min-max-ve-clamp-fonksiyonlari",
		title: "CSS'te Min, Max ve Clamp Fonksiyonları",
		description: "CSS yazarken hayatımızı kolaylaştıran bazı fonksiyonlar var. Bazı durumlarda kullanılan genişlik, font-size gibi değerlerin dinamik olarak...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2021-06-27",
		coverImage: "/blog/2021/06-27/min-max-ve-clamp-caniuse.png",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/csste-min-max-ve-clamp-fonksiyonlari"
	},
	{
		slug: "/renk-kontrastini-hesaplama",
		title: "Renk Kontrastını Hesaplama",
		description: "Bu makalede, arka plan rengine bağlı olarak yazı rengini değiştirmeyi göreceğiz. CSS tarafında bir yazıya verdiğimizi düşünelim. Koyu arka plan...",
		category: "technical",
		tags: ["JavaScript"],
		locale: "tr",
		published: true,
		publishedAt: "2021-05-29",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/renk-kontrastini-hesaplama"
	},
	{
		slug: "/cep-herkulu-naim-suleymanoglu",
		title: "Cep Herkülü: Naim Süleymanoğlu",
		description: "2019 Kasım ayında gösterime girmiş olan, dünya rekortmeni Naim Süleymanoğlu'nın filmini çokça görmeme rağmen yeni izleyebildim. Ben Naim...",
		category: "personal",
		tags: ["Film"],
		locale: "tr",
		published: true,
		publishedAt: "2021-05-08",
		coverImage: "/blog/2021/05-08/naim.jpg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/cep-herkulu-naim-suleymanoglu",
		mediumUrl: "https://omergulcicek.medium.com/cep-herkülü-naim-süleymanoğlu-1d92dc35dc3c"
	},
	{
		slug: "/css-mantiksal-ozellikler",
		title: "CSS Mantıksal Özellikler",
		description: "Web site geliştirirken varsayılan olarak yazı dilimiz soldan sağa (_Left to Right - LTR_) kullanıyoruz. Arapça gibi sağdan sola doğru okuma yönü olan...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2021-03-28",
		coverImage: "/blog/2021/03-28/css-logical-properties.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/css-mantiksal-ozellikler"
	},
	{
		slug: "/miyop-lazer-goz-ameliyati",
		title: "Miyop Lazer Göz Ameliyatı",
		description: "Tam hatırlamıyorum ama sanırım ortaokulun son zamanlarından beri gözlük kullanıyorum, yani neredeyse tüm gençliğimi gözlüklü geçirdim. Havuz/denize...",
		category: "personal",
		tags: ["Deneyim"],
		locale: "tr",
		published: true,
		publishedAt: "2021-03-26",
		coverImage: "/blog/2021/03-26/ameliyattan-ciktiktan-sonra.jpg",
		readingTimeMinutes: 6,
		canonicalUrl: "https://omergulcicek.com/blog/miyop-lazer-goz-ameliyati",
		mediumUrl: "https://omergulcicek.medium.com/miyop-lazer-göz-ameliyatı-c1052dba0d82"
	},
	{
		slug: "/macbook-pro-m1-deneyimlerim",
		title: "MacBook Pro M1 Deneyimlerim",
		description: "Apple Kasım 2020 itibari ile kendi üretimi olan M1 işlemcisini duyurdu; Macbook Air/Pro/Mini modellerini de M1 CPU ile baştan geliştirildi....",
		category: "personal",
		tags: ["Deneyim"],
		locale: "tr",
		published: true,
		publishedAt: "2021-02-22",
		coverImage: "/blog/2021/02-22/macbook-pro.jpg",
		readingTimeMinutes: 5,
		canonicalUrl: "https://omergulcicek.com/blog/macbook-pro-m1-deneyimlerim"
	},
	{
		slug: "/japonizm",
		title: "Japonizm",
		description: "Japonya, teknolojisi ve çalışkanlığıyla her zaman gönlümde taht kuran ülkelerden birisidir. Japonya imparatorunun makam odasını gördükten sonrada...",
		category: "personal",
		tags: ["Kitap"],
		locale: "tr",
		published: true,
		publishedAt: "2021-02-21",
		coverImage: "/blog/2021/02-21/japonizm.jpg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/japonizm",
		mediumUrl: "https://omergulcicek.medium.com/japonizm-3b096d73bfc"
	},
	{
		slug: "/react-componentini-npm-paketi-yapmak",
		title: "React Componentini NPM Paketi Yapmak",
		description: "Site geliştirirken sağ tarafta çıkan scroll bar'ları her zaman gizlemeyi tercih ettim. Çok sağlıklı bir yol olmayabilir fakat sayfanın tasarımını...",
		category: "technical",
		tags: ["React", "npm"],
		locale: "tr",
		published: true,
		publishedAt: "2021-01-22",
		coverImage: "/blog/2021/01-22/react-npm-template.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/react-componentini-npm-paketi-yapmak"
	},
	{
		slug: "/2021-hedeflerim",
		title: "2021 Hedeflerim",
		description: "Yeni bir yıl, yeni hayaller, yeni hedefler... 2021 yılı için yeni hedefler belirleyip kendime bir liste oluşturmak istiyorum. Genelde bu tür...",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2021-01-02",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2021-hedeflerim",
		series: "yillik-degerlendirme",
		seriesOrder: 4
	},
	{
		slug: "/2020-degerlendirmesi",
		title: "2020 Değerlendirmesi",
		description: "Her yıl gelenek haline getirdiğim biten yılın değerlendirmesi ve yeni yıl hedefleri makaleme bu senede devam ediyorum. Blog sitemin teknik alt...",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2020-12-31",
		coverImage: "/blog/2020/12-31/volkswagen.jpg",
		readingTimeMinutes: 5,
		canonicalUrl: "https://omergulcicek.com/blog/2020-degerlendirmesi",
		mediumUrl: "https://omergulcicek.medium.com/2020-de%C4%9Ferlendirmesi-7d9cf6017aee",
		series: "yillik-degerlendirme",
		seriesOrder: 3
	},
	{
		slug: "/the-queens-gambit",
		title: "The Queen's Gambit",
		description: "Netflix yapımı The Queen's Gambit, toplam 7 bölümden oluşan bir mini dizi; yani devamı gelmeyecek. Türkçeye kraliçenin gambiti olarak çevriliyor olsa...",
		category: "personal",
		tags: ["Dizi"],
		locale: "tr",
		published: true,
		publishedAt: "2020-11-29",
		coverImage: "/blog/2020/11-29/bobby-fischer.jpg",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/the-queens-gambit",
		mediumUrl: "https://omergulcicek.medium.com/the-queens-gambit-15044bbc40a8"
	},
	{
		slug: "/mjml-ile-responsive-mail-template",
		title: "MJML ile Responsive Mail Template",
		description: "Frontend Developer'ların en büyük baş belası sanırım mail template kodlamaktır. Hem her CSS koduna izin vermiyor, hemde e-posta servisleri (_Gmail,...",
		category: "technical",
		tags: ["HTML"],
		locale: "tr",
		published: true,
		publishedAt: "2020-11-13",
		coverImage: "/blog/2020/11-13/mjml.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/mjml-ile-responsive-mail-template"
	},
	{
		slug: "/linkleri-yeni-sekmede-acmak",
		title: "Linkleri Yeni Sekmede Açmak",
		description: "HTML geliştirme yaparken bir linki yeni sayfada açılmasını istediğimizde linke attribute olarak ekleriz. React geliştirme yaparken eğer yukarıdaki...",
		category: "technical",
		tags: ["HTML"],
		locale: "tr",
		published: true,
		publishedAt: "2020-10-30",
		coverImage: "/blog/2020/10-30/blank.png",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/linkleri-yeni-sekmede-acmak"
	},
	{
		slug: "/focus-ve-focus-within-farki",
		title: "Focus ve Focus-Within Farkı",
		description: "CSS'te , , , gibi bazı pseudo class'lar (sözde sınıf) vardır. Bugün pseudo class'lardan ve in farkını göreceğiz. Makale sonunda iki farklı örnek...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2020-10-10",
		coverImage: "/blog/2020/10-10/focus.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/focus-ve-focus-within-farki"
	},
	{
		slug: "/google-fontlari-daha-hizli-yuklemek",
		title: "Google Fontları Daha Hızlı Yüklemek",
		description: "Web sitenizde Google Font kullanıyorsanız, basit birkaç adım ile daha hızlı yükleme sürelerine ulaşabilirsiniz. Öncelikle bu sitede kullandığım Inter...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2020-09-26",
		coverImage: "/blog/2020/09-26/without-preconnect.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/google-fontlari-daha-hizli-yuklemek"
	},
	{
		slug: "/resimlerde-srcset-kullanimi",
		title: "Resimlerde srcset Kullanımı",
		description: "HTTP Arşivine göre, tipik bir mobil web sayfasının ağırlığı 2.6 MB'nin üzerindedir ve bu ağırlığın üçte ikisinden fazlası resimlerdir. Resimleri en...",
		category: "technical",
		tags: ["HTML"],
		locale: "tr",
		published: true,
		publishedAt: "2020-09-13",
		coverImage: "/blog/2020/09-13/kedi.jpeg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/resimlerde-srcset-kullanimi"
	},
	{
		slug: "/logolari-css-ile-hizalama",
		title: "Logoları CSS ile Hizalama",
		description: "Bir frontend geliştirici olarak, kişisel sitenizin portfolyo sayfasında müşterilerinizin logolarını listelediğiniz bir bölüm oluşturmuş...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2020-09-12",
		coverImage: "/blog/2020/09-12/hizalama-1.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/logolari-css-ile-hizalama"
	},
	{
		slug: "/2019-degerlendirmesi",
		title: "2019 Değerlendirmesi",
		description: "2018'in sonunda yeni yıl hedeflerimi belirtmiştim. Bunlarda ne kadar başarılı olduğumu Z raporu gibi oluşturmak istedim. İlk olarak 2019'da neleri...",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2019-12-31",
		coverImage: "/blog/2019/12-31/calendar.png",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/2019-degerlendirmesi",
		series: "yillik-degerlendirme",
		seriesOrder: 2
	},
	{
		slug: "/gunumuz-turkiyesi-2019",
		title: "Günümüz Türkiyesi 2019",
		description: "Sürekli gözlem yapıp, gözlemlerimi değerlendirmeyi severim. Uzun süredir içimden kendimle konuştuğum bazı konuları Twitter hesabımdan paylaştım....",
		category: "personal",
		tags: ["Düşünce"],
		locale: "tr",
		published: true,
		publishedAt: "2019-01-08",
		coverImage: "/blog/2019/01-08/memur.jpeg",
		readingTimeMinutes: 6,
		canonicalUrl: "https://omergulcicek.com/blog/gunumuz-turkiyesi-2019",
		mediumUrl: "https://medium.com/t%C3%BCrkiye/g%C3%BCn%C3%BCm%C3%BCz-t%C3%BCrkiyesi-46bd7a8c69f6"
	},
	{
		slug: "/the-imitation-game",
		title: "The Imitation Game",
		description: "2014 yılında çekilmiş olan “The Imitation Game” adlı filmi izledim, beğendim ve kaçırdığım detaylar olabilir diye sonraki gün filmi tekrar izledim....",
		category: "personal",
		tags: ["Film"],
		locale: "tr",
		published: true,
		publishedAt: "2018-12-03",
		coverImage: "/blog/2018/12-03/benedict-cumberbatch.jpeg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/the-imitation-game",
		mediumUrl: "https://medium.com/t%C3%BCrkiye/the-imitation-game-204530b0581b"
	},
	{
		slug: "/2018-yili-hedeflerim",
		title: "2018 Yılı Hedeflerim",
		description: "Merhaba ! İyisiyle kötüsüyle 2017 yılınıda geride bıraktık. Bu makalede geride bıraktığımız yıl içerisinde yaşadıklarımı anlatıp, yeni yıldaki...",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2018-01-01",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2018-yili-hedeflerim",
		series: "yillik-degerlendirme",
		seriesOrder: 1
	},
	{
		slug: "/jsx-nedir",
		title: "JSX Nedir?",
		description: "Böyle bir değişken tanımladığımızı düşünün: Bu string yada HTML değildir. Buna JSX denir, JavaScript için bir syntax uzantısıdır. JSX, React...",
		category: "technical",
		tags: ["React"],
		locale: "tr",
		published: true,
		publishedAt: "2017-12-30",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/jsx-nedir"
	},
	{
		slug: "/bind-fonksiyonu",
		title: "Bind() Fonksiyonu",
		description: "Merhaba ! Son haftalarda sürekli olarak React JS üzerine yoğunlaşıyorum ve kendimi bu alanda geliştirmeye devam ediyorum. React JS dokümantasyonunu...",
		category: "technical",
		tags: ["JavaScript", "React"],
		locale: "tr",
		published: true,
		publishedAt: "2017-12-23",
		coverImage: "/blog/2017/12-23/17-1.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/bind-fonksiyonu"
	},
	{
		slug: "/walter-isaacson-gelecegi-kesfedenler",
		title: "Walter Isaacson - Geleceği Keşfedenler",
		description: "Yazılım alanındaki kişilerin birçoğunun idolleri arasında Steve Jobs üstadımız bulunuyor. Bu tür kişilerin hayatları, yaptıkları hep ilgi çekici...",
		category: "personal",
		tags: ["Kitap"],
		locale: "tr",
		published: true,
		publishedAt: "2017-12-09",
		coverImage: "/blog/2017/12-09/walter-isaacson-gelecegi-kesfedenler.jpg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/walter-isaacson-gelecegi-kesfedenler"
	},
	{
		slug: "/resimleri-gorunurse-yuklemek",
		title: "Resimleri Görünürse Yüklemek",
		description: "Merhaba ! Farzedelim ki sitenize giren ziyaretçi yavaş bir internete sahip. Haliyle sitenize girdiğinde yüksek çözünürlüklü fotoğrafları hemen...",
		category: "technical",
		tags: ["JavaScript"],
		locale: "tr",
		published: true,
		publishedAt: "2017-12-08",
		coverImage: "/blog/2017/12-08/15-1.gif",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/resimleri-gorunurse-yuklemek"
	},
	{
		slug: "/gitstats-v2-github-api",
		title: "GitStats v2 - GitHub API",
		description: "Merhaba ! Bir önceki blog yazımda GitHub'ta bir projeye katkı yapan kişilerin isimlerini, kaç commit katkı yaptıklarını ve yüzdelik olarak katkısını...",
		category: "technical",
		tags: ["GitHub", "JavaScript"],
		locale: "tr",
		published: true,
		publishedAt: "2017-11-20",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/gitstats-v2-github-api"
	},
	{
		slug: "/gitstats",
		title: "GitStats",
		description: "Merhaba ! GitHub'ta herhangi bir projede Insights sekmesinden Contributors linkine tıklarsak, o projeye kimin ne kadar katkı yaptığını detaylı olarak...",
		category: "technical",
		tags: ["GitHub", "JavaScript"],
		locale: "tr",
		published: true,
		publishedAt: "2017-11-18",
		coverImage: "/blog/2017/11-18/13-1.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/gitstats"
	},
	{
		slug: "/devtools-ile-javascript-debug",
		title: "DevTools ile JavaScript Debug",
		description: "Merhaba ! Yeni bir JavaScript geliştiricisiyseniz, yazdığınız kodda çıkacak olan hataları nasıl çözeceğiniz konusunda zorlanabilirsiniz. İlk zamanlar...",
		category: "technical",
		tags: ["JavaScript"],
		locale: "tr",
		published: true,
		publishedAt: "2017-11-14",
		coverImage: "/blog/2017/11-14/12-1.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/devtools-ile-javascript-debug"
	},
	{
		slug: "/is-bulmak",
		title: "İş Bulmak",
		description: "30'dan önce 30 30'dan önce 30 listemde, 30 yaşına gelene kadar yapmak istediklerimi listeledim. Bu listeleri birçok blogger arkadaşımız hazırlamış....",
		category: "personal",
		tags: ["Deneyim"],
		locale: "tr",
		published: true,
		publishedAt: "2017-10-13",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/is-bulmak"
	},
	{
		slug: "/photopea-com",
		title: "Photopea.com",
		description: "Merhaba ! Frontend Developer'lar olarak büyük çoğunluğumuz Adobe Photoshop'a, bir arayüzü html'e dökecek kadar hakimiz. Fakat şirketlerimizdeki...",
		category: "technical",
		tags: ["Frontend"],
		locale: "tr",
		published: true,
		publishedAt: "2017-10-07",
		coverImage: "/blog/2017/10-07/10-1.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/photopea-com"
	},
	{
		slug: "/jquery-ile-css-important",
		title: "jQuery ile CSS important",
		description: "Merhaba ! CSS'te ki söz hiyerarşisi şu şekildedir. İlk öncelik, (_varsa_) inline css olarak yazılmış css kodundadır. Ardından css dosyamızdaki...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2017-09-30",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/jquery-ile-css-important"
	},
	{
		slug: "/position-sticky",
		title: "Position: Sticky",
		description: "Merhaba ! CSS'te position özelliğinin _absolute_, _relative_, _fixed_ gibi sık kullandığımız özellikleri yanında pek görmediğimiz ama çok işe yarayan...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2017-08-19",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/position-sticky"
	},
	{
		slug: "/change-title",
		title: "Başlık Değiştirme",
		description: "Merhaba ! Twitter'da gezerken Emir Karşıyakalı'nın bir tweet'ine denk geldim. enuygun.com sitesinde işlem yaparken farklı bir tab'a geçtiğinizde...",
		category: "technical",
		tags: ["JavaScript", "GitHub"],
		locale: "tr",
		published: true,
		publishedAt: "2017-08-05",
		coverImage: "/blog/2017/08-05/7-1.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/change-title"
	},
	{
		slug: "/box-shadowa-guclu-alternatif-drop-shadow",
		title: "Box Shadow'a güçlü alternatif: Drop Shadow",
		description: "Merhaba ! Çoğunuzunda bildiği gibi CSS ile bir nesneye gölge vermek için box-shadow kullanırız. Fakat box-shadow'un hatalı gölgelendirme yaptığı...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2017-07-28",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/box-shadowa-guclu-alternatif-drop-shadow"
	},
	{
		slug: "/css-framework-anket-sonuclari",
		title: "CSS Framework Anket Sonuçları",
		description: "Facebook üzerinden CSS Framework anketi yapmıştım. Anketin (_bu makaleyi yazarken_) 118 yanıtı var. Tek tek sorulara verilen yanıtları inceleyelim....",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2017-07-26",
		coverImage: "/blog/2017/07-26/5-1.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/css-framework-anket-sonuclari"
	},
	{
		slug: "/reading-time-paketi",
		title: "Reading Time Paketi",
		description: "Merhaba ! Sitemin arayüzünü yenilerken başka bir blog sitesinde, yazılan makalelerin üstünde tahmini olarak okunma süresinin yazdığını gördüm....",
		category: "technical",
		tags: ["npm"],
		locale: "tr",
		published: true,
		publishedAt: "2017-07-25",
		coverImage: "/blog/2017/07-25/4-1.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/reading-time-paketi"
	},
	{
		slug: "/sait-kosk-hemdem",
		title: "Sait Köşk - Hemdem",
		description: "30 yaşından önce yapmak istediğim şeyleri, 30'dan önce 30 listemde sıralamıştım. Listede ki maddelerin birisi de toplam 100 kitap okumaktı. Tavsiye...",
		category: "personal",
		tags: ["Kitap"],
		locale: "tr",
		published: true,
		publishedAt: "2017-07-22",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/sait-kosk-hemdem"
	},
	{
		slug: "/kartvizit-tasarimim",
		title: "Kartvizit Tasarımım",
		description: "Selamünaleyküm. Uzun zamandır kendime kartvizit yapmayı çok istedim. Sıfırdan çizecek tasarım bilgim olmadığı için hazır tasarımlara yöneldim....",
		category: "personal",
		tags: ["Proje"],
		locale: "tr",
		published: true,
		publishedAt: "2017-05-15",
		coverImage: "/blog/2017/05-15/2-1.png",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/kartvizit-tasarimim"
	},
	{
		slug: "/turkuaz-css",
		title: "Turkuaz CSS",
		description: "Merhaba ! Web geliştirme ile ilgileniyorsanız framework'leri mutlaka duymuş yada kullanmışsınızdır. Artık günümüzde responsive olmayan bir tasarım...",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2017-05-07",
		coverImage: "/blog/2017/05-07/1-2.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/turkuaz-css"
	}
]
