import type { BlogPost } from "@/features/blog/types/blog.types"

export const MOCK_BLOG_POSTS: BlogPost[] = [
	{
		slug: "/apex",
		title: "Apex",
		description: "Tek başına yola çıkan bir dağcının keşif yolculuğu, kısa sürede ölümcül bir kovalamacaya dönüşüyor.",
		category: "personal",
		tags: ["Film"],
		locale: "tr",
		published: true,
		publishedAt: "2026-07-01",
		coverImage: "/blog/2026/07-01/apex.jpg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/apex"
	},
	{
		slug: "/nextjsten-tanstack-ve-supabasee-gecis",
		title: "Next.js'ten TanStack ve Supabase'e Geçiş",
		description: "Kişisel sitemi güncel teknolojilere taşıdım; Next.js ve MDX yapısını TanStack ve Supabase ile yeniden kurguladım.",
		category: "technical",
		tags: ["Site Yenileme", "TanStack", "Supabase"],
		locale: "tr",
		published: true,
		publishedAt: "2026-07-01",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/nextjsten-tanstack-ve-supabasee-gecis",
		series: "site-yenileme",
		seriesOrder: 4
	},
	{
		slug: "/virastack-ai",
		title: "ViraStack AI: Yapay Zekâya Mimari Disiplin",
		description: "Yapay zekâyla kod yazarken her seferinde aynı kuralları baştan anlatmak zorunda kalmayın. ViraStack AI, tutarlı kod üretimi için açık kaynak bir kural seti.",
		category: "technical",
		tags: ["ViraStack", "Yapay Zekâ"],
		locale: "tr",
		published: true,
		publishedAt: "2026-06-30",
		coverImage: "/blog/2026/04-05/virastack.jpeg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/virastack-ai",
		series: "virastack",
		seriesOrder: 2
	},
	{
		slug: "/footy-futbol-bilgini-sahaya-yansit",
		title: "Footy: Futbol Bilgini Sahaya Yansıt",
		description: "Gerçek futbol tutkunlarını tek bir çatı altında toplayan, futbol bilgisini eğlenceye ve kıyasıya bir rekabete dönüştüren Footy platformu yayında!",
		category: "personal",
		tags: ["Proje"],
		locale: "tr",
		published: true,
		publishedAt: "2026-06-28",
		coverImage: "/blog/2026/06-28/futbol-manyagi.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/footy-futbol-bilgini-sahaya-yansit",
		mediumUrl: "https://omergulcicek.medium.com/futbol-bilgini-sahaya-yans%C4%B1t-footy-ile-rekabete-haz%C4%B1r-m%C4%B1s%C4%B1n-6877cba0208e"
	},
	{
		slug: "/ilgi-alanlarinizi-tek-tikla-takviminize-ekleyin",
		title: "İlgi Alanlarınızı Tek Tıkla Takviminize Ekleyin",
		description: "Tematik takvim abonelikleri projesinin güncellenmesiyle ilgili alanlarına tek tıkla takviminize nasıl ekleyeceğiniz.",
		category: "personal",
		tags: ["Proje"],
		locale: "tr",
		published: true,
		publishedAt: "2026-06-28",
		coverImage: "/blog/2026/06-28/takvim-onizleme.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/ilgi-alanlarinizi-tek-tikla-takviminize-ekleyin",
		mediumUrl: "https://medium.com/@omergulcicek/i%CC%87lgi-alanlar%C4%B1n%C4%B1z%C4%B1-tek-t%C4%B1kla-takviminize-ekleyin-98ea44e1ee52"
	},
	{
		slug: "/medya-kusatmasi-ve-ruhsuz-egitim-manevi-bosluktaki-zombi-nesil",
		title: "Medya Kuşatması ve Ruhsuz Eğitim: Manevi Boşluktaki Zombi Nesil",
		description: "Toplumun manevi köklerini yitirdiği bir dönemde medya, eğitim ve gençlik üzerine kaleme aldığım sert bir bakış.",
		category: "personal",
		tags: ["Düşünce"],
		locale: "tr",
		published: true,
		publishedAt: "2026-04-16",
		coverImage: "/blog/2026/04-16/diziler.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/medya-kusatmasi-ve-ruhsuz-egitim-manevi-bosluktaki-zombi-nesil"
	},
	{
		slug: "/dijital-bir-hayalet-gunlugu",
		title: "Dijital Bir Hayalet Günlüğü",
		description: "Algoritmaların popülizm iştahı ile derin içerik arasında sıkışan dijital üreticiliğe dair samimi bir bakış.",
		category: "personal",
		tags: ["Düşünce"],
		locale: "tr",
		published: true,
		publishedAt: "2026-04-09",
		coverImage: "/blog/2026/04-08/omer-demirbag.jpeg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/dijital-bir-hayalet-gunlugu"
	},
	{
		slug: "/frontend-ekosistemi-insa-etmek",
		title: "ViraStack: Frontend Ekosistemi",
		description: "ViraStack nasıl doğdu? Turkuaz CSS'ten açık kaynak bir frontend ekosistemine uzanan kişisel yolculuğum ve bu yapının arkasındaki motivasyon.",
		category: "technical",
		tags: ["ViraStack"],
		locale: "tr",
		published: true,
		publishedAt: "2026-04-05",
		coverImage: "/blog/2026/04-05/virastack.jpeg",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/frontend-ekosistemi-insa-etmek",
		featured: true,
		mediumUrl: "https://omergulcicek.medium.com/frontend-ekosistemi-insa-etmek-78111c2d96dc",
		series: "virastack",
		seriesOrder: 1
	},
	{
		slug: "/gelenekten-gelecege-ramazan-adabi-ve-teknik-hedefler",
		title: "Gelenekten Geleceğe: Ramazan Adabı",
		description: "Unutulmaya yüz tutmuş gelenekleri modern hayata taşıma niyetiyle hazırladığım kültürel Ramazan notları.",
		category: "personal",
		tags: ["Düşünce"],
		locale: "tr",
		published: true,
		publishedAt: "2026-02-17",
		coverImage: "/blog/2026/02-17/ramazan.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/gelenekten-gelecege-ramazan-adabi-ve-teknik-hedefler",
		mediumUrl: "https://medium.com/@omergulcicek/gelenekten-gelece%C4%9Fe-ramazan-adab%C4%B1-ve-teknik-hedefler-589dfd1d8b72"
	},
	{
		slug: "/kaide-ai-native-architecture-kit",
		title: "Kaide: AI-Native Architecture Kit",
		description: "An architectural standard optimized for modern web projects, making code more readable and manageable for AI assistants: Kaide Architecture Kit.",
		category: "technical",
		tags: ["Next.js", "TanStack"],
		locale: "en",
		published: true,
		publishedAt: "2026-02-14",
		coverImage: "/blog/2026/02-14/kaide.png",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/kaide-ai-native-architecture-kit",
		featured: true,
		translationOf: "/kaide-yapay-zeka-odakli-mimari-kit"
	},
	{
		slug: "/kaide-yapay-zeka-odakli-mimari-kit",
		title: "Kaide: Yapay Zekâ Odaklı Mimari Kit",
		description: "Yapay zeka asistanlarıyla uyumlu, modern web projeleri için optimize edilmiş, okunabilir ve yönetilebilir bir mimari standardı: Kaide Architecture Kit.",
		category: "technical",
		tags: ["Next.js", "TanStack"],
		locale: "tr",
		published: true,
		publishedAt: "2026-02-14",
		coverImage: "/blog/2026/02-14/kaide.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/kaide-yapay-zeka-odakli-mimari-kit",
		mediumUrl: "https://omergulcicek.medium.com/kaide-yapay-zek%C3%A2-odakl%C4%B1-mimari-kit-d323a9b81552",
		translatedTo: "/kaide-ai-native-architecture-kit"
	},
	{
		slug: "/documentation-for-machines-llms-txt",
		title: "Documentation for Machines: llms.txt",
		description: "We are now targeting AI agents in the web world. This article explores how to use the llms.txt format to make projects more readable for LLMs.",
		category: "technical",
		tags: ["Yapay Zekâ"],
		locale: "en",
		published: true,
		publishedAt: "2026-02-04",
		coverImage: "/blog/2026/02-04/llms.png",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/documentation-for-machines-llms-txt",
		translationOf: "/makineler-icin-dokumantasyon-llms-txt"
	},
	{
		slug: "/makineler-icin-dokumantasyon-llms-txt",
		title: "Makineler İçin Dokümantasyon: llms.txt",
		description: "LLM'ler ve yapay zekâ ajanları için llms.txt formatının ne olduğunu ve projelere nasıl entegre edilebileceğini anlatan rehber.",
		category: "technical",
		tags: ["Yapay Zekâ"],
		locale: "tr",
		published: true,
		publishedAt: "2026-02-04",
		coverImage: "/blog/2026/02-04/llms.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/makineler-icin-dokumantasyon-llms-txt",
		translatedTo: "/documentation-for-machines-llms-txt"
	},
	{
		slug: "/tanstack-start-injected-head-scripts-hatasi-cozumu",
		title: "TanStack Start: tanstack-start-injected-head-scripts Hatası ve Çözümü",
		description: "TanStack Start projelerinde karşılaşılan injected head scripts hidrasyon hatasının kök nedeni ve uygulanan çözüm.",
		category: "technical",
		tags: ["TanStack", "Supabase", "Vite"],
		locale: "tr",
		published: true,
		publishedAt: "2026-02-03",
		coverImage: "/blog/2026/02-03/injected.png",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/tanstack-start-injected-head-scripts-hatasi-cozumu",
		mediumUrl: "https://medium.com/@omergulcicek/tanstack-start-tanstack-start-injected-head-scripts-hatas%C4%B1-ve-%C3%A7%C3%B6z%C3%BCm%C3%BC-69de117093a0",
		translatedTo: "/tanstack-start-resolving-the-tanstack-start-injected-head-scripts-error"
	},
	{
		slug: "/tanstack-start-resolving-the-tanstack-start-injected-head-scripts-error",
		title: "TanStack Start: Resolving the tanstack-start-injected-head-scripts Error",
		description: "Causes and solutions for the 'Injected head scripts' hydration error encountered in TanStack Start projects, especially when using plugins like Supabase.",
		category: "technical",
		tags: ["TanStack", "Supabase", "Vite"],
		locale: "en",
		published: true,
		publishedAt: "2026-02-03",
		coverImage: "/blog/2026/02-03/injected.png",
		readingTimeMinutes: 5,
		canonicalUrl: "https://omergulcicek.com/blog/tanstack-start-resolving-the-tanstack-start-injected-head-scripts-error",
		mediumUrl: "https://medium.com/@omergulcicek/tanstack-start-resolving-the-tanstack-start-injected-head-scripts-error-c1eecbf31735",
		translationOf: "/tanstack-start-injected-head-scripts-hatasi-cozumu"
	},
	{
		slug: "/see",
		title: "See",
		description: "Görmenin günah sayıldığı distopik bir dünyada geçen Apple TV+ dizisi See hakkında spoiler içermeyen kısa değerlendirme.",
		category: "personal",
		tags: ["Dizi"],
		locale: "tr",
		published: true,
		publishedAt: "2026-02-02",
		coverImage: "/blog/future/see.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/see"
	},
	{
		slug: "/react-state-yonetim-mimarisi",
		title: "React State Yönetim Mimarisi",
		description: "Hangi kütüphane sorusundan önce state'in doğasını tanımlamayı merkeze alan üst düzey React state mimarisi yaklaşımı.",
		category: "technical",
		tags: ["React", "TanStack"],
		locale: "tr",
		published: true,
		publishedAt: "2026-02-01",
		coverImage: "/blog/2026/02-01/passing-props.png",
		readingTimeMinutes: 6,
		canonicalUrl: "https://omergulcicek.com/blog/react-state-yonetim-mimarisi",
		mediumUrl: "https://medium.com/@omergulcicek/react-state-y%C3%B6netim-mimarisi-cec5ad6043fb"
	},
	{
		slug: "/2026-icin-react-ve-yapay-zeka-stacki",
		title: "2026 için React ve Yapay Zekâ Stack'i",
		description: "2026'da React ve yapay zekâ araçlarını birlikte konumlandırmaya dair Builder.io makalesinin deneyimle zenginleştirilmiş çevirisi.",
		category: "technical",
		tags: ["Frontend", "Yapay Zekâ"],
		locale: "tr",
		published: true,
		publishedAt: "2026-01-28",
		coverImage: "/blog/2026/01-28/react-stack.png",
		readingTimeMinutes: 6,
		canonicalUrl: "https://omergulcicek.com/blog/2026-icin-react-ve-yapay-zeka-stacki",
		featured: true
	},
	{
		slug: "/2025ten-2026ya-degerlendirme-ve-hedefler",
		title: "2025'ten 2026'ya: Değerlendirme ve Hedefler",
		description: "Yerleşik düzenin değiştiği, üretkenliğin ve önceliklerin yeniden tanımlandığı bir dönemin ardından önümüze baktığım kapsamlı yazı.",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2026-01-01",
		coverImage: "/blog/2025/12-31/github-3.png",
		readingTimeMinutes: 6,
		canonicalUrl: "https://omergulcicek.com/blog/2025ten-2026ya-degerlendirme-ve-hedefler",
		series: "yillik-degerlendirme",
		seriesOrder: 10
	},
	{
		slug: "/2026da-hayatimiza-girecek-yeni-css-ozellikleri",
		title: "2026'da Hayatımıza Girecek Yeni CSS Özellikleri",
		description: "Tarayıcı desteği ve pratik kullanım açısından yakın dönemde hayatımıza girebilecek CSS yeniliklerine dair teknik bir derleme.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2025-12-25",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2026da-hayatimiza-girecek-yeni-css-ozellikleri",
		interactive: true,
		featured: true,
		mediumUrl: "https://omergulcicek.medium.com/2026da-hayat%C4%B1m%C4%B1za-girecek-yeni-css-%C3%B6zellikleri-f48158357b77"
	},
	{
		slug: "/yapay-zeka-caginda-frontend-bitti-mi",
		title: "Yapay Zekâ Çağında Frontend Bitti mi?",
		description: "'Frontend bitti' söyleminin ötesinde, sektör daralması mı dönüşüm mü olduğunu sorgulayan güncel bir mesleki değerlendirme.",
		category: "technical",
		tags: ["Frontend", "Yapay Zekâ"],
		locale: "tr",
		published: true,
		publishedAt: "2025-12-01",
		coverImage: "/blog/2025/12-01/frontend.png",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/yapay-zeka-caginda-frontend-bitti-mi"
	},
	{
		slug: "/yan-yana",
		title: "Yan Yana",
		description: "Can Dostum'dan uyarlanan Yan Yana filminde Haluk Bilginer ve Feyyaz Yiğit'in performansına dair spoiler'sız kısa bir bakış.",
		category: "personal",
		tags: ["Film"],
		locale: "tr",
		published: true,
		publishedAt: "2025-11-28",
		coverImage: "/blog/2025/11-28/yan-yana.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/yan-yana"
	},
	{
		slug: "/yapay-zekanin-sorunlari",
		title: "Yapay Zekânın Sorunları",
		description: "Addy Osmani'nin AI's 70% Problem yazısından süzülen özet ve yapay zekâ destekli geliştirmede yaşadığım somut deneyimler.",
		category: "technical",
		tags: ["Yapay Zekâ"],
		locale: "tr",
		published: true,
		publishedAt: "2025-11-18",
		coverImage: "/blog/2025/11-18/addy-osmani.png",
		readingTimeMinutes: 5,
		canonicalUrl: "https://omergulcicek.com/blog/yapay-zekanin-sorunlari",
		mediumUrl: "https://omergulcicek.medium.com/yapay-zek%C3%A2n%C4%B1n-sorunlar%C4%B1-57ab1bf5e335?postPublishedType=initial"
	},
	{
		slug: "/nizam-nextjs-16-boilerplate",
		title: "Nizam: Next.js 16 Boilerplate",
		description: "Modern web uygulamalarını hızlı, güvenli ve ölçeklenebilir bir şekilde inşa etmek için hazırladığım Next.js 16 boilerplate projesi: Nizam.",
		category: "technical",
		tags: ["Next.js", "TanStack"],
		locale: "tr",
		published: true,
		publishedAt: "2025-11-06",
		coverImage: "/blog/2025/11-05/nizam.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/nizam-nextjs-16-boilerplate",
		mediumUrl: "https://omergulcicek.medium.com/nizam-next-js-16-boilerplate-3015d8945f39",
		translatedTo: "/nizam-nextjs-16-boilerplate-en"
	},
	{
		slug: "/nizam-nextjs-16-boilerplate-en",
		title: "Nizam: Next.js 16 Boilerplate",
		description: "Introducing Nizam: A Next.js 16 boilerplate designed to build modern web applications quickly, securely, and enjoyably.",
		category: "technical",
		tags: ["Next.js", "TanStack"],
		locale: "en",
		published: true,
		publishedAt: "2025-11-05",
		coverImage: "/blog/2025/11-05/nizam.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/nizam-nextjs-16-boilerplate-en",
		mediumUrl: "https://omergulcicek.medium.com/nizam-next-js-16-boilerplate-en-59fdf4872f3f",
		translationOf: "/nizam-nextjs-16-boilerplate"
	},
	{
		slug: "/nextjs-16-turbopack-cache-components-ve-yeni-mimari-donemi",
		title: "Next.js 16: Turbopack, Cache Components ve Yeni Mimari Dönemi",
		description: "Next.js 16 sürümünde Turbopack, Cache Components ve App Router tarafındaki mimari yeniliklere dair teknik bir bakış.",
		category: "technical",
		tags: ["Next.js"],
		locale: "tr",
		published: true,
		publishedAt: "2025-10-23",
		coverImage: "/blog/2025/10-23/nextjs-16.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/nextjs-16-turbopack-cache-components-ve-yeni-mimari-donemi",
		featured: true,
		mediumUrl: "https://omergulcicek.medium.com/next-js-16-turbopack-cache-components-ve-yeni-mimari-d%C3%B6nemi-5ed8018ccde1"
	},
	{
		slug: "/google-maps-kisisel-listelerim",
		title: "Google Maps: Kişisel Listelerim",
		description: "Gezdiğim yerleri Google Maps kişisel listeleriyle nasıl kaydettiğimi ve bu alışkanlığın seyahat ritmine etkisini anlatan notlar.",
		category: "personal",
		tags: ["Deneyim"],
		locale: "tr",
		published: true,
		publishedAt: "2025-10-20",
		coverImage: "/blog/2025/10-20/google-maps.png",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/google-maps-kisisel-listelerim",
		mediumUrl: "https://omergulcicek.medium.com/google-maps-listelerim-83291fedbc9d"
	},
	{
		slug: "/kaliteli-yazilimci-nasil-olunur",
		title: "Kaliteli Yazılımcı Nasıl Olunur?",
		description: "On yılı aşkın sektör deneyiminden süzülen; teknik beceri, üretkenlik ve iletişim ekseninde kaliteli yazılımcılık üzerine düşünceler.",
		category: "technical",
		tags: ["Frontend"],
		locale: "tr",
		published: true,
		publishedAt: "2025-10-14",
		coverImage: "/blog/2025/10-14/yazilimci.png",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/kaliteli-yazilimci-nasil-olunur",
		mediumUrl: "https://omergulcicek.medium.com/kaliteli-yaz%C4%B1l%C4%B1mc%C4%B1-nas%C4%B1l-olunur-9b357ae2bc3c"
	},
	{
		slug: "/fatih-sultan-mehmed-dogunun-ve-batinin-efendisi",
		title: "Fâtih Sultan Mehmed - Doğu’nun ve Batı’nın Efendisi",
		description: "İlber Ortaylı'nın kaleminden Fatih Sultan Mehmed'i fetihlerinin ötesinde bir lider ve düşünce insanı olarak okumak.",
		category: "personal",
		tags: ["Kitap"],
		locale: "tr",
		published: true,
		publishedAt: "2025-10-02",
		coverImage: "/blog/2025/10-02/fatih.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/fatih-sultan-mehmed-dogunun-ve-batinin-efendisi"
	},
	{
		slug: "/takvim-abonelikleri-zamani-zenginlestirin",
		title: "Takvim Abonelikleri: Zamanı Zenginleştirin",
		description: "Apple Takvim'e tek tıkla abone olunabilen tematik etkinlik takvimleri projesi; ilgi alanlarınızı rutininize taşıma fikri.",
		category: "personal",
		tags: ["Deneyim"],
		locale: "tr",
		published: true,
		publishedAt: "2025-09-19",
		coverImage: "/blog/2025/09-19/takvim-ornek.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/takvim-abonelikleri-zamani-zenginlestirin"
	},
	{
		slug: "/gunumuz-turkiyesi-2025",
		title: "Günümüz Türkiyesi 2025",
		description: "Sert konuşmadan ama meseleyi es geçmeden; sokak, ekran ve iş hayatından süzülen güncel gözlemler ile çözüm önerileri.",
		category: "personal",
		tags: ["Düşünce"],
		locale: "tr",
		published: true,
		publishedAt: "2025-09-16",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/gunumuz-turkiyesi-2025"
	},
	{
		slug: "/frontend-calisma-ortamim-cursor-eklentiler",
		title: "Frontend Çalışma Ortamım: Cursor, Eklentiler ve Daha Fazlası",
		description: "Cursor'dan tarayıcı eklentilerine, klasör yapısından kod standartlarına uzanan kişisel frontend çalışma ortamımın paylaşımı.",
		category: "technical",
		tags: ["Yapay Zekâ"],
		locale: "tr",
		published: true,
		publishedAt: "2025-08-13",
		coverImage: "/blog/2025/08-13/calisma-masam.JPG",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/frontend-calisma-ortamim-cursor-eklentiler",
		mediumUrl: "https://omergulcicek.medium.com/frontend-%C3%A7al%C4%B1%C5%9Fma-ortam%C4%B1m-cursor-eklentiler-ve-daha-fazlas%C4%B1-d0b63064fe25"
	},
	{
		slug: "/nextjs-15-ile-tasarim-ve-mimari-yenilemesi",
		title: "Next.js 15 ile Tasarım ve Mimari Yenilemesi",
		description: "Kişisel sitemi yeniden tasarladım; full-width düzenden container layout'a geçip ana sayfa, avatar ve arama deneyimini yeniden kurguladım.",
		category: "technical",
		tags: ["Site Yenileme", "Next.js"],
		locale: "tr",
		published: true,
		publishedAt: "2025-07-27",
		coverImage: "/blog/2025/07-27/avatars.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/nextjs-15-ile-tasarim-ve-mimari-yenilemesi",
		mediumUrl: "https://omergulcicek.medium.com/sitemin-yeni-aray%C3%BCz%C3%BCne-ho%C5%9Fgeldiniz-126ce241ea47",
		series: "site-yenileme",
		seriesOrder: 3
	},
	{
		slug: "/nevsehir-tatili",
		title: "Nevşehir Tatili",
		description: "2025 yazında Kapadokya'nın atmosferini keşfetmek için Nevşehir'e yapılan kısa tatilin kişisel notları.",
		category: "personal",
		tags: ["Seyahat"],
		locale: "tr",
		published: true,
		publishedAt: "2025-07-26",
		coverImage: "/blog/2025/07-26/balon.JPG",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/nevsehir-tatili",
		mediumUrl: "https://omergulcicek.medium.com/nev%C5%9Fehir-tatili-16233f3723be"
	},
	{
		slug: "/nextjs-15-boilerplate",
		title: "Next.js 15 Boilerplate",
		description: "Next.js 15, TanStack Query ve güncel frontend araçlarıyla kurduğum açık kaynak boilerplate projesinin mimari ve özellikleri.",
		category: "technical",
		tags: ["Next.js", "TypeScript", "shadcn/ui"],
		locale: "tr",
		published: true,
		publishedAt: "2025-07-23",
		coverImage: "/blog/2025/07-23/boilerplate.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/nextjs-15-boilerplate",
		mediumUrl: "https://omergulcicek.medium.com/next-js-15-boilerplate-7d34c8be6b16"
	},
	{
		slug: "/react-parola-inputlari-icin-goster-gizle-hooku",
		title: "React Parola Inputları İçin Göster/Gizle Hooku",
		description: "Parola alanlarına göster/gizle işlevi eklemek için geliştirdiğim @omergulcicek/password-input hook'unun kullanım rehberi.",
		category: "technical",
		tags: ["React", "npm"],
		locale: "tr",
		published: true,
		publishedAt: "2025-06-19",
		coverImage: "/blog/2025/06-16/password-input.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/react-parola-inputlari-icin-goster-gizle-hooku",
		mediumUrl: "https://omergulcicek.medium.com/react-parola-inputlar%C4%B1-i%C3%A7in-g%C3%B6ster-gizle-hooku-1f0085624887"
	},
	{
		slug: "/react-hook-form-icin-akilli-mask-ve-dogrulama",
		title: "React Hook Form İçin Akıllı Mask ve Doğrulama",
		description: "@omergulcicek/forms paketiyle React Hook Form projelerinde maskeleme ve doğrulama işlemlerini kolaylaştırmanın pratik kullanımı.",
		category: "technical",
		tags: ["React", "npm"],
		locale: "tr",
		published: true,
		publishedAt: "2025-06-09",
		coverImage: "/blog/2025/06-09/forms-mask.png",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/react-hook-form-icin-akilli-mask-ve-dogrulama",
		mediumUrl: "https://medium.com/kodcular/react-hook-form-i%C3%A7in-ak%C4%B1ll%C4%B1-mask-ve-do%C4%9Frulama-97dfe79d9123"
	},
	{
		slug: "/css-attr-icin-yeni-yetkinlikler",
		title: "CSS attr() İçin Yeni Yetkinlikler",
		description: "attr() fonksiyonunun string dışı değerler döndürmeye başlamasıyla CSS'te açılan yeni kullanım olanaklarına dair pratik bir inceleme.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2025-03-22",
		coverImage: "/blog/2025/03-22/css-attr.png",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/css-attr-icin-yeni-yetkinlikler",
		mediumUrl: "https://omergulcicek.medium.com/css-attr-i%CC%87%C3%A7in-yeni-yetkinlikler-47c9b2fabe10"
	},
	{
		slug: "/tailwind-css-v4",
		title: "Tailwind CSS v4",
		description: "Frontend dünyasında popülerleşen Tailwind CSS, v4.0 sürümüyle karşımıza çıktı. Yeni sürümüyle esneklik ve performansı artırıyor.",
		category: "technical",
		tags: ["Tailwind CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2025-02-07",
		coverImage: "/blog/2025/01-29/tailwind-css-v4.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/tailwind-css-v4",
		mediumUrl: "https://omergulcicek.medium.com/tailwind-css-v4-0-7678b29262f3?source=user_profile_page"
	},
	{
		slug: "/2025-yilinda-frontend-developer-olmak",
		title: "2025 Yılında Frontend Developer Olmak",
		description: "Bootstrap'tan Tailwind'e, jQuery'den React ekosistemine uzanan frontend dünyasında bugün ne bilmek gerektiğine dair güncel bir rehber.",
		category: "technical",
		tags: ["Next.js", "TanStack", "TypeScript"],
		locale: "tr",
		published: true,
		publishedAt: "2025-01-20",
		coverImage: "/blog/2025/01-20/react-typescript.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2025-yilinda-frontend-developer-olmak",
		mediumUrl: "https://omergulcicek.medium.com/2025-y%C4%B1l%C4%B1nda-frontend-developer-olmak-774e74ae355c"
	},
	{
		slug: "/react-virtualization-buyuk-verilerin-ekranda-verimli-gosterimi",
		title: "React Virtualization: Büyük Verilerin Ekranda Verimli Gösterimi",
		description: "Binlerce satırlık listelerde React Virtualization ile yalnızca görünen öğeleri render ederek performans kazanmanın mantığı.",
		category: "technical",
		tags: ["React"],
		locale: "tr",
		published: true,
		publishedAt: "2025-01-10",
		coverImage: "/blog/2025/01-10/virtualization.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/react-virtualization-buyuk-verilerin-ekranda-verimli-gosterimi",
		mediumUrl: "https://omergulcicek.medium.com/react-virtualization-b%C3%BCy%C3%BCk-verilerin-ekranda-verimli-g%C3%B6sterimi-a91b9e6c6e37"
	},
	{
		slug: "/react-19-ile-gelen-yenilik-use-optimistic-hook-kullanimi",
		title: "React 19 ile Gelen Yenilik: useOptimistic Hook Kullanımı",
		description: "React 19'un useOptimistic hook'u ile sunucu yanıtını beklemeden UI güncelleme akışını kurmanın pratik örneği.",
		category: "technical",
		tags: ["React"],
		locale: "tr",
		published: true,
		publishedAt: "2025-01-06",
		coverImage: "/blog/2025/01-06/useOptimistic.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/react-19-ile-gelen-yenilik-use-optimistic-hook-kullanimi",
		mediumUrl: "https://omergulcicek.medium.com/react-19-ile-gelen-yenilik-useoptimistic-hook-kullan%C4%B1m%C4%B1-eebe5cb6a732"
	},
	{
		slug: "/frontendin-parlayan-yildizi-shadcn-ui-ile-tanisin",
		title: "Frontend''in Parlayan Yıldızı: shadcn/ui ile Tanışın",
		description: "Radix UI ve Tailwind üzerine kurulu shadcn/ui'nin bileşen modelini, avantajlarını ve kullanım yaklaşımını tanıtan rehber.",
		category: "technical",
		tags: ["shadcn/ui"],
		locale: "tr",
		published: true,
		publishedAt: "2025-01-04",
		coverImage: "/blog/2025/01-04/shadcn-ui.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/frontendin-parlayan-yildizi-shadcn-ui-ile-tanisin",
		mediumUrl: "https://omergulcicek.medium.com/frontendin-parlayan-y%C4%B1ld%C4%B1z%C4%B1-shadcn-ui-ile-tan%C4%B1%C5%9F%C4%B1n-d0e6b821b4ec"
	},
	{
		slug: "/2025-hedeflerim",
		title: "2025 Hedeflerim",
		description: "Hayatın merkezinin kayacağı bir döneme hazırlanırken tuttuğum dengeli, somut ve ölçülebilir yol haritası.",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2025-01-01",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/2025-hedeflerim",
		series: "yillik-degerlendirme",
		seriesOrder: 9
	},
	{
		slug: "/2024-degerlendirmesi",
		title: "2024 Değerlendirmesi",
		description: "Tempo düşerken hayatın yönünün değiştiği bir dönemin üzerine tuttuğum, kariyerden kişisel hayata uzanan samimi notlar.",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2024-12-31",
		coverImage: "/blog/2024/12-31/alisgidis.png",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2024-degerlendirmesi",
		series: "yillik-degerlendirme",
		seriesOrder: 8
	},
	{
		slug: "/nextjs-ve-shadcn-ui-ile-site-yenilemesi",
		title: "Next.js ve shadcn/ui ile Site Yenilemesi",
		description: "Kişisel sitemi uzun aradan sonra yeniledim; shadcn/ui tabanlı arayüze yer imleri ve frontend yol haritasını ekledim.",
		category: "technical",
		tags: ["Site Yenileme", "Next.js"],
		locale: "tr",
		published: true,
		publishedAt: "2024-12-29",
		coverImage: "/blog/2024/12-29/filters.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/nextjs-ve-shadcn-ui-ile-site-yenilemesi",
		series: "site-yenileme",
		seriesOrder: 2
	},
	{
		slug: "/2022-degerlendirmesi",
		title: "2022 Değerlendirmesi",
		description: "Şehri yaşamak, üretmek ve sosyalleşmek arasında geçen hareketli bir dönemin enerjisini yansıtan kişisel yılsonu yazısı.",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2022-12-31",
		coverImage: "/blog/2022/12-31/maps.jpg",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2022-degerlendirmesi",
		series: "yillik-degerlendirme",
		seriesOrder: 7
	},
	{
		slug: "/2022-css-istatistikleri",
		title: "2022 CSS İstatistikleri",
		description: "HTTP Archive verilerinden süzülen güncel CSS kullanım istatistikleri; sınıflar, özellikler ve trendler üzerine veriye dayalı bir bakış.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2022-10-09",
		coverImage: "/blog/2022/10-09/en-populer-css-siniflari.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/2022-css-istatistikleri"
	},
	{
		slug: "/grid-template-areas-ile-layout-olusturmak",
		title: "Grid Template Areas ile Layout Oluşturmak",
		description: "CSS Grid'in grid-template-areas özelliğiyle okunabilir ve esnek layout'lar kurmanın pratik bir yaklaşımı.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2022-09-09",
		coverImage: "/blog/2022/09-09/grid-template-areas-ile-layout-olusturmak-1.jpg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/grid-template-areas-ile-layout-olusturmak"
	},
	{
		slug: "/css-object-view-box",
		title: "CSS Object View Box",
		description: "Görüntüleri ek sarmalayıcı olmadan kırpmak için object-view-box özelliğinin ne sunduğunu ve nasıl kullanıldığını gösteren rehber.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2022-06-26",
		coverImage: "/blog/2022/06-26/crop-image-css.png",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/css-object-view-box"
	},
	{
		slug: "/gatsbyden-nextjse-gecis",
		title: "Gatsby'den Next.js'e Geçiş",
		description: "Kişisel sitemi yeniledim; Gatsby tabanlı statik yapıyı Next.js SSG ve Tailwind CSS ile yeniden kurguladım.",
		category: "technical",
		tags: ["Site Yenileme", "Next.js"],
		locale: "tr",
		published: true,
		publishedAt: "2022-04-22",
		coverImage: "/blog/2022/04-22/renk.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/gatsbyden-nextjse-gecis",
		series: "site-yenileme",
		seriesOrder: 1
	},
	{
		slug: "/styled-component-ile-dinamik-css-yazmak",
		title: "Styled Component ile Dinamik CSS Yazmak",
		description: "JSON'dan gelen stilleri Styled Components ile dinamik olarak render eden component mimarisinin problemi ve çözümü.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2022-01-25",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/styled-component-ile-dinamik-css-yazmak"
	},
	{
		slug: "/2022-hedeflerim",
		title: "2022 Hedeflerim",
		description: "Rutinden çıkıp şehri keşfetmeye, sosyalleşmeye ve üretmeye odaklandığım daha hareketli bir dönemin yol haritası.",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2022-01-01",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2022-hedeflerim",
		mediumUrl: "https://omergulcicek.medium.com/2022-hedeflerim-69c889488716",
		series: "yillik-degerlendirme",
		seriesOrder: 6
	},
	{
		slug: "/2021-degerlendirmesi",
		title: "2021 Değerlendirmesi",
		description: "Mesai sonrasını hayatın farklı alanlarına ayırdığım bir dönemin samimi muhasebesi.",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2021-12-31",
		coverImage: "/blog/2021/12-31/duolingo-2021.jpg",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2021-degerlendirmesi",
		series: "yillik-degerlendirme",
		seriesOrder: 5
	},
	{
		slug: "/css-container-sorgulari",
		title: "CSS Container Sorguları",
		description: "Medya sorgularına complement olarak bileşen bazında responsive davranış kurmayı sağlayan CSS container queries'e giriş.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2021-11-26",
		coverImage: "/blog/2021/11-26/responsive-problem-1.jpg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/css-container-sorgulari"
	},
	{
		slug: "/javascript-selectorlerinin-calisma-hizlari",
		title: "JavaScript Selectorlerinin Çalışma Hızları",
		description: "querySelector, getElementById ve benzeri DOM seçicilerinin performans farklarını ölçerek karşılaştıran teknik inceleme.",
		category: "technical",
		tags: ["JavaScript"],
		locale: "tr",
		published: true,
		publishedAt: "2021-10-29",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/javascript-selectorlerinin-calisma-hizlari"
	},
	{
		slug: "/izmir-marmaris-oludeniz-tatili",
		title: "İzmir, Marmaris, Ölüdeniz Tatili",
		description: "Üniversite arkadaşlarımla İzmir, Marmaris ve Ölüdeniz güzergahında geçen yaz tatilinin kısa anıları.",
		category: "personal",
		tags: ["Seyahat"],
		locale: "tr",
		published: true,
		publishedAt: "2021-08-09",
		coverImage: "/blog/2021/08-09/izmir.jpg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/izmir-marmaris-oludeniz-tatili"
	},
	{
		slug: "/csste-min-max-ve-clamp-fonksiyonlari",
		title: "CSS''te Min, Max ve Clamp Fonksiyonları",
		description: "Dinamik boyutlandırmada min(), max() ve clamp() fonksiyonlarını gerçek senaryolar üzerinden anlatan CSS rehberi.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2021-06-27",
		coverImage: "/blog/2021/06-27/min-max-ve-clamp-caniuse.png",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/csste-min-max-ve-clamp-fonksiyonlari"
	},
	{
		slug: "/renk-kontrastini-hesaplama",
		title: "Renk Kontrastını Hesaplama",
		description: "Arka plan rengine göre yazı rengini JavaScript ile dinamik seçerek okunabilirliği artırmanın pratik yöntemi.",
		category: "technical",
		tags: ["JavaScript"],
		locale: "tr",
		published: true,
		publishedAt: "2021-05-29",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/renk-kontrastini-hesaplama"
	},
	{
		slug: "/cep-herkulu-naim-suleymanoglu",
		title: "Cep Herkülü: Naim Süleymanoğlu",
		description: "Naim Süleymanoğlu'nun sinematografik hikayesini izledikten sonra film hakkında kısa, spoiler içermeyen izlenimlerim.",
		category: "personal",
		tags: ["Film"],
		locale: "tr",
		published: true,
		publishedAt: "2021-05-08",
		coverImage: "/blog/2021/05-08/naim.jpg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/cep-herkulu-naim-suleymanoglu",
		mediumUrl: "https://omergulcicek.medium.com/cep-herkülü-naim-süleymanoğlu-1d92dc35dc3c"
	},
	{
		slug: "/css-mantiksal-ozellikler",
		title: "CSS Mantıksal Özellikler",
		description: "LTR ve RTL dillerde aynı mantığı koruyarak layout yazmayı kolaylaştıran CSS logical properties'e pratik bir giriş.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2021-03-28",
		coverImage: "/blog/2021/03-28/css-logical-properties.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/css-mantiksal-ozellikler"
	},
	{
		slug: "/miyop-lazer-goz-ameliyati",
		title: "Miyop Lazer Göz Ameliyatı",
		description: "Miyop lazer göz ameliyatına karar verme sürecim, operasyon deneyimim ve sonrasında yaşadığım günlük hayat değişiklikleri.",
		category: "personal",
		tags: ["Deneyim"],
		locale: "tr",
		published: true,
		publishedAt: "2021-03-26",
		coverImage: "/blog/2021/03-26/ameliyattan-ciktiktan-sonra.jpg",
		readingTimeMinutes: 6,
		canonicalUrl: "https://omergulcicek.com/blog/miyop-lazer-goz-ameliyati",
		mediumUrl: "https://omergulcicek.medium.com/miyop-lazer-göz-ameliyatı-c1052dba0d82"
	},
	{
		slug: "/macbook-pro-m1-deneyimlerim",
		title: "MacBook Pro M1 Deneyimlerim",
		description: "Intel'den M1 MacBook Pro'ya geçişte performans, pil ömrü ve günlük geliştirme deneyimine dair kişisel izlenimler.",
		category: "personal",
		tags: ["Deneyim"],
		locale: "tr",
		published: true,
		publishedAt: "2021-02-22",
		coverImage: "/blog/2021/02-22/macbook-pro.jpg",
		readingTimeMinutes: 5,
		canonicalUrl: "https://omergulcicek.com/blog/macbook-pro-m1-deneyimlerim"
	},
	{
		slug: "/japonizm",
		title: "Japonizm",
		description: "Teknolojisi, disiplini ve kültürüyle Japonya'ya duyduğum ilgiyi ve gözlemlerimi kaleme aldığım kişisel bir yazı.",
		category: "personal",
		tags: ["Kitap"],
		locale: "tr",
		published: true,
		publishedAt: "2021-02-21",
		coverImage: "/blog/2021/02-21/japonizm.jpg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/japonizm",
		mediumUrl: "https://omergulcicek.medium.com/japonizm-3b096d73bfc"
	},
	{
		slug: "/react-componentini-npm-paketi-yapmak",
		title: "React Componentini NPM Paketi Yapmak",
		description: "Yuvarlak progress bar bileşeninden yola çıkarak bir React paketini npm'e yayınlama sürecinin adım adım anlatımı.",
		category: "technical",
		tags: ["React", "npm"],
		locale: "tr",
		published: true,
		publishedAt: "2021-01-22",
		coverImage: "/blog/2021/01-22/react-npm-template.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/react-componentini-npm-paketi-yapmak"
	},
	{
		slug: "/2021-hedeflerim",
		title: "2021 Hedeflerim",
		description: "Abartmadan ve gerçekçi kalarak, hayatın farklı alanlarına yayılmış niyetleri planlama alışkanlığımın yeni dönem notları.",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2021-01-02",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2021-hedeflerim",
		series: "yillik-degerlendirme",
		seriesOrder: 4
	},
	{
		slug: "/2020-degerlendirmesi",
		title: "2020 Değerlendirmesi",
		description: "Pandemi düzeninde geçen bir yılın notları; kariyer yolculuğumdan kişisel ilgi alanlarıma uzanan geleneksel yılsonu yazım.",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2020-12-31",
		coverImage: "/blog/2020/12-31/volkswagen.jpg",
		readingTimeMinutes: 5,
		canonicalUrl: "https://omergulcicek.com/blog/2020-degerlendirmesi",
		mediumUrl: "https://omergulcicek.medium.com/2020-de%C4%9Ferlendirmesi-7d9cf6017aee",
		series: "yillik-degerlendirme",
		seriesOrder: 3
	},
	{
		slug: "/the-queens-gambit",
		title: "The Queen's Gambit",
		description: "Netflix mini dizisi The Queen's Gambit üzerine satranç, anlatı ve prodüksiyon açısından spoiler'a düşmeden kısa bir değerlendirme.",
		category: "personal",
		tags: ["Dizi"],
		locale: "tr",
		published: true,
		publishedAt: "2020-11-29",
		coverImage: "/blog/2020/11-29/bobby-fischer.jpg",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/the-queens-gambit",
		mediumUrl: "https://omergulcicek.medium.com/the-queens-gambit-15044bbc40a8"
	},
	{
		slug: "/mjml-ile-responsive-mail-template",
		title: "MJML ile Responsive Mail Template",
		description: "E-posta template kodlamasını daha taşınabilir hale getiren MJML ile responsive mail şablonu oluşturmanın temelleri.",
		category: "technical",
		tags: ["HTML"],
		locale: "tr",
		published: true,
		publishedAt: "2020-11-13",
		coverImage: "/blog/2020/11-13/mjml.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/mjml-ile-responsive-mail-template"
	},
	{
		slug: "/linkleri-yeni-sekmede-acmak",
		title: "Linkleri Yeni Sekmede Açmak",
		description: "target=_blank kullanımının erişilebilirlik ve güvenlik boyutlarıyla birlikte doğru uygulanışına dair kısa bir not.",
		category: "technical",
		tags: ["HTML"],
		locale: "tr",
		published: true,
		publishedAt: "2020-10-30",
		coverImage: "/blog/2020/10-30/blank.png",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/linkleri-yeni-sekmede-acmak"
	},
	{
		slug: "/focus-ve-focus-within-farki",
		title: "Focus ve Focus-Within Farkı",
		description: ":focus ile :focus-within pseudo class'larının davranış farkını erişilebilirlik odaklı örneklerle karşılaştıran kısa rehber.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2020-10-10",
		coverImage: "/blog/2020/10-10/focus.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/focus-ve-focus-within-farki"
	},
	{
		slug: "/google-fontlari-daha-hizli-yuklemek",
		title: "Google Fontları Daha Hızlı Yüklemek",
		description: "Google Fonts entegrasyonunda birkaç küçük optimizasyonla font yüklemesini hızlandırmanın pratik yolları.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2020-09-26",
		coverImage: "/blog/2020/09-26/without-preconnect.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/google-fontlari-daha-hizli-yuklemek"
	},
	{
		slug: "/resimlerde-srcset-kullanimi",
		title: "Resimlerde srcset Kullanımı",
		description: "Farklı ekran yoğunlukları için srcset ve sizes ile responsive görüntü optimizasyonuna pratik bir giriş.",
		category: "technical",
		tags: ["HTML"],
		locale: "tr",
		published: true,
		publishedAt: "2020-09-13",
		coverImage: "/blog/2020/09-13/kedi.jpeg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/resimlerde-srcset-kullanimi"
	},
	{
		slug: "/logolari-css-ile-hizalama",
		title: "Logoları CSS ile Hizalama",
		description: "Portfolyo sayfalarında farklı boyutlu müşteri logolarını CSS ile hizalı ve tutarlı göstermenin pratik yöntemi.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2020-09-12",
		coverImage: "/blog/2020/09-12/hizalama-1.png",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/logolari-css-ile-hizalama"
	},
	{
		slug: "/2019-degerlendirmesi",
		title: "2019 Değerlendirmesi",
		description: "Alışkanlıklar, hedef takibi ve yazılım dışına açılan bir dönemin samimi geriye bakışı.",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2019-12-31",
		coverImage: "/blog/2019/12-31/calendar.png",
		readingTimeMinutes: 4,
		canonicalUrl: "https://omergulcicek.com/blog/2019-degerlendirmesi",
		series: "yillik-degerlendirme",
		seriesOrder: 2
	},
	{
		slug: "/gunumuz-turkiyesi-2019",
		title: "Günümüz Türkiyesi 2019",
		description: "Olumsuzluğa kapılmadan ülkenin güncel tablosuna baktığım; sevdiğim için eleştiriyorum diyerek yazdığım düşünce yazısı.",
		category: "personal",
		tags: ["Düşünce"],
		locale: "tr",
		published: true,
		publishedAt: "2019-01-08",
		coverImage: "/blog/2019/01-08/memur.jpeg",
		readingTimeMinutes: 6,
		canonicalUrl: "https://omergulcicek.com/blog/gunumuz-turkiyesi-2019",
		mediumUrl: "https://medium.com/t%C3%BCrkiye/g%C3%BCn%C3%BCm%C3%BCz-t%C3%BCrkiyesi-46bd7a8c69f6"
	},
	{
		slug: "/the-imitation-game",
		title: "The Imitation Game",
		description: "Alan Turing'in hikayesini anlatan The Imitation Game filmi hakkında Benedict Cumberbatch'lı yapım üzerine kısa izlenimler.",
		category: "personal",
		tags: ["Film"],
		locale: "tr",
		published: true,
		publishedAt: "2018-12-03",
		coverImage: "/blog/2018/12-03/benedict-cumberbatch.jpeg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/the-imitation-game",
		mediumUrl: "https://medium.com/t%C3%BCrkiye/the-imitation-game-204530b0581b"
	},
	{
		slug: "/2018-yili-hedeflerim",
		title: "2018 Yılı Hedeflerim",
		description: "İlk iş deneyimlerinden React projelerine uzanan bir dönemin ardından, yeni yıla taşıdığım teknik ve kişisel niyetlerin planı.",
		category: "personal",
		tags: ["Yıl Değerlendirmesi"],
		locale: "tr",
		published: true,
		publishedAt: "2018-01-01",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/2018-yili-hedeflerim",
		series: "yillik-degerlendirme",
		seriesOrder: 1
	},
	{
		slug: "/jsx-nedir",
		title: "JSX Nedir?",
		description: "React dünyasının en temel yapı taşlarından JSX'in ne olduğunu, neden var olduğunu ve nasıl çalıştığını anlatan giriş yazısı.",
		category: "technical",
		tags: ["React"],
		locale: "tr",
		published: true,
		publishedAt: "2017-12-30",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/jsx-nedir"
	},
	{
		slug: "/bind-fonksiyonu",
		title: "Bind() Fonksiyonu",
		description: "React örnekleri üzerinden JavaScript bind() fonksiyonunun ne işe yaradığını ve this bağlamını nasıl yönettiğini anlatan kısa bir rehber.",
		category: "technical",
		tags: ["JavaScript", "React"],
		locale: "tr",
		published: true,
		publishedAt: "2017-12-23",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/bind-fonksiyonu"
	},
	{
		slug: "/walter-isaacson-gelecegi-kesfedenler",
		title: "Walter Isaacson - Geleceği Keşfedenler",
		description: "Walter Isaacson'un Geleceği Keşfedenler kitabından Steve Jobs, Bill Gates ve dönemin teknoloji öncülerine dair okuma notları.",
		category: "personal",
		tags: ["Kitap"],
		locale: "tr",
		published: true,
		publishedAt: "2017-12-09",
		coverImage: "/blog/2017/12-09/walter-isaacson-gelecegi-kesfedenler.jpg",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/walter-isaacson-gelecegi-kesfedenler"
	},
	{
		slug: "/resimleri-gorunurse-yuklemek",
		title: "Resimleri Görünürse Yüklemek",
		description: "Viewport dışındaki görselleri gereksiz yere yüklememek için lazy loading yaklaşımının temel mantığı ve uygulaması.",
		category: "technical",
		tags: ["JavaScript"],
		locale: "tr",
		published: true,
		publishedAt: "2017-12-08",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/resimleri-gorunurse-yuklemek"
	},
	{
		slug: "/gitstats-v2-github-api",
		title: "GitStats v2 - GitHub API",
		description: "GitHub API ile proje katkı istatistiklerini çeken GitStats aracının ikinci versiyonu ve geliştirme sürecindeki dersler.",
		category: "technical",
		tags: ["GitHub", "JavaScript"],
		locale: "tr",
		published: true,
		publishedAt: "2017-11-20",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/gitstats-v2-github-api"
	},
	{
		slug: "/gitstats",
		title: "GitStats",
		description: "GitHub projelerindeki katkı dağılımını saf JavaScript ile tabloya döken küçük bir araç ve kullanım rehberi.",
		category: "technical",
		tags: ["GitHub", "JavaScript"],
		locale: "tr",
		published: true,
		publishedAt: "2017-11-18",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/gitstats"
	},
	{
		slug: "/devtools-ile-javascript-debug",
		title: "DevTools ile JavaScript Debug",
		description: "console.log'a mahkum kalmadan Chrome DevTools ile JavaScript hatalarını adım adım izlemenin temel yolları.",
		category: "technical",
		tags: ["JavaScript"],
		locale: "tr",
		published: true,
		publishedAt: "2017-11-14",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/devtools-ile-javascript-debug"
	},
	{
		slug: "/is-bulmak",
		title: "İş Bulmak",
		description: "30'dan önce 30 listemin 21. maddesi: iş bulma ve başvuru sürecinde edindiğim deneyimlerden süzülen kişisel notlar.",
		category: "personal",
		tags: ["Deneyim"],
		locale: "tr",
		published: true,
		publishedAt: "2017-10-13",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/is-bulmak"
	},
	{
		slug: "/photopea-com",
		title: "Photopea.com",
		description: "Adobe Photoshop'a ücretsiz alternatif Photopea ile arayüz geliştiricilerinin günlük iş akışına nasıl entegre edilebileceği.",
		category: "technical",
		tags: ["Frontend"],
		locale: "tr",
		published: true,
		publishedAt: "2017-10-07",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/photopea-com"
	},
	{
		slug: "/jquery-ile-css-important",
		title: "jQuery ile CSS important",
		description: "jQuery ile inline stillere !important eklemenin CSS özgüllük hiyerarşisi içindeki yeri ve pratik kullanımı.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2017-09-30",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/jquery-ile-css-important"
	},
	{
		slug: "/position-sticky",
		title: "Position: Sticky",
		description: "CSS position sticky özelliğinin scroll davranışı, kullanım sınırları ve pratik senaryolar üzerinden anlatımı.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2017-08-19",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/position-sticky"
	},
	{
		slug: "/change-title",
		title: "Başlık Değiştirme",
		description: "Sekmeler arasında kalan süreyi sayfa başlığında gösterme fikrini koddan geçirerek nasıl uygulayabileceğinizi anlatan küçük bir JavaScript örneği.",
		category: "technical",
		tags: ["JavaScript", "GitHub"],
		locale: "tr",
		published: true,
		publishedAt: "2017-08-05",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/change-title"
	},
	{
		slug: "/box-shadowa-guclu-alternatif-drop-shadow",
		title: "Box Shadow''a güçlü alternatif: Drop Shadow",
		description: "Box-shadow'un yetersiz kaldığı senaryolarda filter drop-shadow ile daha gerçekçi gölge vermenin pratik çözümü.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2017-07-28",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/box-shadowa-guclu-alternatif-drop-shadow"
	},
	{
		slug: "/css-framework-anket-sonuclari",
		title: "CSS Framework Anket Sonuçları",
		description: "Topluluk anketi sonuçları üzerinden CSS framework tercihlerine, alışkanlıklara ve sektörel eğilimlere dair veriye dayalı bir yorum.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2017-07-26",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/css-framework-anket-sonuclari"
	},
	{
		slug: "/reading-time-paketi",
		title: "Reading Time Paketi",
		description: "Blog yazılarına tahmini okuma süresi eklemek için geliştirdiğim reading-time paketinin kullanımı ve motivasyonu.",
		category: "technical",
		tags: ["npm"],
		locale: "tr",
		published: true,
		publishedAt: "2017-07-25",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/reading-time-paketi"
	},
	{
		slug: "/sait-kosk-hemdem",
		title: "Sait Köşk - Hemdem",
		description: "Sait Köşk'ün Hemdem kitabına dair kısa okuma notları; okuma listemdeki 11. kitap üzerine samimi bir izlenim.",
		category: "personal",
		tags: ["Kitap"],
		locale: "tr",
		published: true,
		publishedAt: "2017-07-22",
		readingTimeMinutes: 2,
		canonicalUrl: "https://omergulcicek.com/blog/sait-kosk-hemdem"
	},
	{
		slug: "/kartvizit-tasarimim",
		title: "Kartvizit Tasarımım",
		description: "Kendi kartvizitimi sıfırdan tasarlayıp basma sürecindeki tasarım tercihleri ve kişisel deneyimlerim.",
		category: "personal",
		tags: ["Proje"],
		locale: "tr",
		published: true,
		publishedAt: "2017-05-15",
		readingTimeMinutes: 1,
		canonicalUrl: "https://omergulcicek.com/blog/kartvizit-tasarimim"
	},
	{
		slug: "/turkuaz-css",
		title: "Turkuaz CSS",
		description: "Kendi geliştirdiğim Turkuaz CSS framework'ünün motivasyonu, özellikleri ve responsive arayüz geliştirmedeki yeri.",
		category: "technical",
		tags: ["CSS"],
		locale: "tr",
		published: true,
		publishedAt: "2017-05-07",
		readingTimeMinutes: 3,
		canonicalUrl: "https://omergulcicek.com/blog/turkuaz-css"
	}
]
