/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as StackRouteImport } from './routes/stack'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as DevMdxSandboxRouteImport } from './routes/dev/mdx-sandbox'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as OgBlogSlugRouteImport } from './routes/og/blog/$slug'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMdxSandboxRoute = DevMdxSandboxRouteImport.update({
  id: '/dev/mdx-sandbox',
  path: '/dev/mdx-sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgBlogSlugRoute = OgBlogSlugRouteImport.update({
  id: '/og/blog/$slug',
  path: '/og/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/experiences': typeof ExperiencesRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/journey': typeof JourneyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stack': typeof StackRoute
  '/workspace': typeof WorkspaceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dev/mdx-sandbox': typeof DevMdxSandboxRoute
  '/blog/': typeof BlogIndexRoute
  '/og/blog/$slug': typeof OgBlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/experiences': typeof ExperiencesRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/journey': typeof JourneyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stack': typeof StackRoute
  '/workspace': typeof WorkspaceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dev/mdx-sandbox': typeof DevMdxSandboxRoute
  '/blog': typeof BlogIndexRoute
  '/og/blog/$slug': typeof OgBlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/experiences': typeof ExperiencesRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/journey': typeof JourneyRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stack': typeof StackRoute
  '/workspace': typeof WorkspaceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dev/mdx-sandbox': typeof DevMdxSandboxRoute
  '/blog/': typeof BlogIndexRoute
  '/og/blog/$slug': typeof OgBlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/bookmarks'
    | '/experiences'
    | '/feed.xml'
    | '/journey'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/stack'
    | '/workspace'
    | '/blog/$slug'
    | '/dev/mdx-sandbox'
    | '/blog/'
    | '/og/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/bookmarks'
    | '/experiences'
    | '/feed.xml'
    | '/journey'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/stack'
    | '/workspace'
    | '/blog/$slug'
    | '/dev/mdx-sandbox'
    | '/blog'
    | '/og/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/bookmarks'
    | '/experiences'
    | '/feed.xml'
    | '/journey'
    | '/projects'
    | '/services'
    | '/sitemap.xml'
    | '/stack'
    | '/workspace'
    | '/blog/$slug'
    | '/dev/mdx-sandbox'
    | '/blog/'
    | '/og/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  BookmarksRoute: typeof BookmarksRoute
  ExperiencesRoute: typeof ExperiencesRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  JourneyRoute: typeof JourneyRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StackRoute: typeof StackRoute
  WorkspaceRoute: typeof WorkspaceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DevMdxSandboxRoute: typeof DevMdxSandboxRoute
  BlogIndexRoute: typeof BlogIndexRoute
  OgBlogSlugRoute: typeof OgBlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/mdx-sandbox': {
      id: '/dev/mdx-sandbox'
      path: '/dev/mdx-sandbox'
      fullPath: '/dev/mdx-sandbox'
      preLoaderRoute: typeof DevMdxSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/blog/$slug': {
      id: '/og/blog/$slug'
      path: '/og/blog/$slug'
      fullPath: '/og/blog/$slug'
      preLoaderRoute: typeof OgBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  BookmarksRoute: BookmarksRoute,
  ExperiencesRoute: ExperiencesRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  JourneyRoute: JourneyRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StackRoute: StackRoute,
  WorkspaceRoute: WorkspaceRoute,
  BlogSlugRoute: BlogSlugRoute,
  DevMdxSandboxRoute: DevMdxSandboxRoute,
  BlogIndexRoute: BlogIndexRoute,
  OgBlogSlugRoute: OgBlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
